window.ASSISTANT_CONFIG = {
  "lang": "en",
  "endpoint": "https://formsubmit.co/info@shroyalschools.ng",
  "speechLang": "en-US",
  "strings": {
    "title": "Digital Academic Assistant",
    "subtitle": "Sultan Hanafi Royal Schools",
    "disclosure": "I'm an AI assistant, not a staff member — I can answer questions about the school and help with schoolwork, but for anything official please use the contact details below.",
    "greeting": "Hello! Choose a topic below, or type your own question about the school or your schoolwork.",
    "inputPlaceholder": "Ask about admissions, programmes, or get help with schoolwork…",
    "send": "Send",
    "stop": "Stop",
    "thinking": "Thinking",
    "listening": "Listening…",
    "micLabel": "Speak your question",
    "micStopLabel": "Stop listening",
    "micUnsupported": "Voice input isn't supported in this browser — try Chrome or Edge.",
    "speakToggleOn": "Read replies aloud: on",
    "speakToggleOff": "Read replies aloud: off",
    "uploadLabel": "Attach a document or image",
    "uploadUnsupported": "That file type isn't supported. Try a PDF, Word document, plain text, or an image.",
    "uploadTooLarge": "That file is too large — please keep attachments under 8 MB.",
    "uploadReading": "Reading attachment…",
    "uploadReadError": "Couldn't read that file — please try another.",
    "attachmentRemove": "Remove attachment",
    "errorGeneric": "Something went wrong — please try again in a moment.",
    "newChat": "New conversation",
    "contactToggle": "Talk to our admissions team",
    "namePlaceholder": "Your full name",
    "contactPlaceholder": "Email or phone",
    "emailSubject": "New admissions enquiry — Digital Assistant",
    "sendLabel": "Send my details",
    "sendingLabel": "Sending…",
    "sentConfirmation": "Thank you — our admissions team will be in touch shortly.",
    "sendError": "Couldn't send just now — please reach us directly via WhatsApp, phone, or email below.",
    "longConversation": "This conversation has gotten long. Please start a new conversation so I can keep answering accurately.",
    "continueOnWhatsapp": "Continue on WhatsApp →",
    "whatsappPrefill": "Hello, I was chatting with your digital assistant about:"
  },
  "starters": [
    { "label": "Our four institutions", "prompt": "What are the four institutions at Sultan Hanafi Royal Schools, and how do they differ?" },
    { "label": "Admissions process", "prompt": "Walk me through your admissions process, step by step." },
    { "label": "Boarding facility", "prompt": "Tell me about the boarding facility — who is it for and what does it involve?" },
    { "label": "Help with schoolwork", "prompt": "Can you help me revise a topic for school?" }
  ]
};
