/* Language switcher runtime.
 *
 * Loaded after js/locale-registry.js and js/i18n-core.js (both generated by
 * scripts/build.js from i18n/locales.json and lib/i18n.js — edit those, not
 * the generated copies).
 *
 * Two switching strategies, chosen per page rather than globally:
 *
 *   INSTANT  — the page carries [data-i18n] attributes covering its chrome
 *              (the 69 portal pages). Switching rewrites text in place,
 *              flips dir/lang, and never touches the URL. No reload, so an
 *              open form keeps its values, a dashboard keeps its fetched
 *              data, and the session cookie is never re-negotiated.
 *   NAVIGATE — the page is a pre-rendered static document whose prose only
 *              exists in the locale tree (the public site). The translated
 *              text is a different file, so a navigation is unavoidable —
 *              but we navigate to the SAME page in the target language,
 *              carrying the query string and hash, so the reader lands
 *              where they were rather than on a foreign homepage.
 *
 * Preference is stored in BOTH localStorage (for this runtime) and a cookie
 * (so an edge function or a future server render can honour it before any
 * JavaScript runs). They are written together and read localStorage-first.
 */
(function () {
  'use strict';

  var I18N = window.SHRS_I18N;
  if (!I18N) return; // core failed to load — leave the page as built

  var STORE_KEY = 'shrsLocale';
  var COOKIE = 'shrs_locale';
  var REDIRECT_GUARD = 'shrsLocaleRedirected';
  var DICT_BASE = '/i18n/';

  var dicts = {}; // code -> flat dictionary, lazily fetched

  // --- Preference storage --------------------------------------------------
  function readStored() {
    var v = null;
    try { v = window.localStorage.getItem(STORE_KEY); } catch (e) { /* private mode */ }
    if (!v) {
      var m = document.cookie.match(new RegExp('(?:^|; )' + COOKIE + '=([^;]*)'));
      if (m) v = decodeURIComponent(m[1]);
    }
    return v && I18N.isKnown(v) ? v : null;
  }

  function writeStored(code) {
    try { window.localStorage.setItem(STORE_KEY, code); } catch (e) { /* not fatal */ }
    // One year, site-wide, lax: enough for "remember me next visit" without
    // being sent on cross-site requests.
    document.cookie = COOKIE + '=' + encodeURIComponent(code) +
      ';path=/;max-age=31536000;samesite=lax';
  }

  // --- Dictionary loading --------------------------------------------------
  // Only the ACTIVE language's dictionary is ever fetched, and only on a
  // page that can use it (instant-mode pages). Static pages are already
  // rendered in their language and need no dictionary at all — which is why
  // the public site pays nothing for this system at load time.
  function loadDict(code) {
    if (dicts[code]) return Promise.resolve(dicts[code]);
    return fetch(DICT_BASE + code + '.json', { credentials: 'same-origin' })
      .then(function (r) {
        if (!r.ok) throw new Error('dictionary ' + code + ' HTTP ' + r.status);
        return r.json();
      })
      .then(function (json) { dicts[code] = json; return json; })
      .catch(function () { dicts[code] = {}; return dicts[code]; });
  }

  // --- Current locale ------------------------------------------------------
  // <html lang> is authoritative because the build stamped it; the path is
  // the fallback for any hand-authored page that forgot to.
  function currentLocale() {
    var declared = document.documentElement.getAttribute('lang');
    if (declared && I18N.isKnown(declared)) return declared;
    return I18N.localeFromPath(window.location.pathname);
  }

  // --- Instant mode --------------------------------------------------------
  function pageSupportsInstant() {
    return document.querySelector('[data-i18n]') !== null;
  }

  /* Applies a dictionary over the page. Three attribute forms are honoured:
       data-i18n            -> element text
       data-i18n-attr="..." -> a comma-separated list of attr:key pairs, for
                               placeholder/title/aria-label, which are just as
                               visible to a reader as body text
       data-i18n-html       -> innerHTML, for the few strings carrying markup
     Anything without a translation is left exactly as the build rendered it,
     so a partial dictionary degrades to mixed language rather than to blanks. */
  function applyDict(code) {
    var doc = document;
    doc.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      var val = I18N.translate(dicts, code, key);
      if (val.charAt(0) !== '⟦') el.textContent = val; // skip ⟦missing⟧
    });
    doc.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      var val = I18N.translate(dicts, code, key);
      if (val.charAt(0) !== '⟦') el.innerHTML = val;
    });
    doc.querySelectorAll('[data-i18n-attr]').forEach(function (el) {
      el.getAttribute('data-i18n-attr').split(',').forEach(function (pair) {
        var bits = pair.split(':');
        if (bits.length !== 2) return;
        var attr = bits[0].trim();
        var val = I18N.translate(dicts, code, bits[1].trim());
        if (val.charAt(0) !== '⟦') el.setAttribute(attr, val);
      });
    });
  }

  function applyDirection(code) {
    var l = I18N.get(code);
    var html = document.documentElement;
    html.setAttribute('lang', code);
    html.setAttribute('dir', l.dir);
    // Lets CSS target a locale without re-deriving it from lang, and gives
    // the Yoruba/Arabic font stacks a stable hook (see css/i18n.css).
    html.setAttribute('data-locale', code);
  }

  function switchInstant(code) {
    return loadDict(code).then(function () {
      applyDirection(code);
      applyDict(code);
      writeStored(code);
      renderSwitcher(code);
      try {
        document.dispatchEvent(new CustomEvent('shrs:locale-changed', {
          detail: { locale: code, dir: I18N.get(code).dir },
        }));
      } catch (e) { /* CustomEvent unsupported — nothing downstream depends on it */ }
    });
  }

  // --- Navigate mode -------------------------------------------------------
  function switchNavigate(code) {
    writeStored(code);
    // Mark this as a deliberate choice so the arrival-side auto-redirect
    // below does not immediately bounce the visitor somewhere else.
    try { window.sessionStorage.setItem(REDIRECT_GUARD, '1'); } catch (e) { /* fine */ }
    window.location.href = I18N.resolvedPathFor(window.location.href, code);
  }

  function switchTo(code) {
    if (!I18N.isKnown(code) || code === currentLocale()) return;
    if (pageSupportsInstant()) switchInstant(code);
    else switchNavigate(code);
  }

  // --- The control ---------------------------------------------------------
  /* Renders into every [data-locale-switcher] mount the build placed in the
     chrome. A <details> disclosure is used rather than a custom popup: it is
     keyboard-operable, screen-reader-announced and Escape-closable for free,
     and it still works if this script's own listeners never attach. */
  function renderSwitcher(active) {
    var mounts = document.querySelectorAll('[data-locale-switcher]');
    if (!mounts.length) return;
    var activeLocale = I18N.get(active);

    mounts.forEach(function (mount) {
      var items = I18N.locales().map(function (l) {
        var isActive = l.code === active;
        var href = pageSupportsInstant() ? '#' : I18N.resolvedPathFor(window.location.href, l.code);
        return '<li><a role="menuitem" href="' + href + '"' +
          ' hreflang="' + l.hreflang + '"' +
          ' lang="' + l.code + '"' +
          ' dir="' + l.dir + '"' +
          ' data-locale-option="' + l.code + '"' +
          (isActive ? ' aria-current="true"' : '') +
          '>' + escapeHtml(l.nativeName) + '</a></li>';
      }).join('');

      mount.innerHTML =
        '<details class="lang-switch" data-lang-switch>' +
          '<summary aria-label="' + escapeAttr(I18N.translate(dicts, active, 'a11y.languageSwitcher')) + '">' +
            '<span class="lang-switch-globe" aria-hidden="true">' +
              '<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.5">' +
              '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.7 2.5 15.3 0 18M12 3c-2.5 2.7-2.5 15.3 0 18"/>' +
              '</svg>' +
            '</span>' +
            '<span class="lang-switch-label" lang="' + active + '">' + escapeHtml(activeLocale.nativeName) + '</span>' +
          '</summary>' +
          '<ul role="menu" class="lang-switch-menu">' + items + '</ul>' +
        '</details>';
    });
  }

  function escapeHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function escapeAttr(s) { return escapeHtml(s).replace(/"/g, '&quot;'); }

  // One delegated listener on the document, so switchers injected later
  // (the portal builds its topbar at runtime) work without re-binding.
  document.addEventListener('click', function (ev) {
    var opt = ev.target.closest && ev.target.closest('[data-locale-option]');
    if (!opt) return;
    var code = opt.getAttribute('data-locale-option');
    if (pageSupportsInstant()) {
      ev.preventDefault();
      switchTo(code);
      // Only close the disclosure on this path. Collapsing <details> in the
      // navigate case removes the anchor from the rendering tree while the
      // click is still being processed, and the browser then declines to
      // follow the href — the switcher would store the preference and go
      // nowhere. The navigating page is about to be replaced anyway, so
      // there is nothing to tidy up there.
      var host = opt.closest('[data-lang-switch]');
      if (host) host.removeAttribute('open');
      return;
    }
    // Let the browser follow the real href — it is a genuine URL, so
    // middle-click, "open in new tab" and copy-link all behave normally.
    // We only record the preference on the way out.
    writeStored(code);
    try { window.sessionStorage.setItem(REDIRECT_GUARD, '1'); } catch (e) { /* fine */ }
  });

  document.addEventListener('keydown', function (ev) {
    if (ev.key !== 'Escape') return;
    document.querySelectorAll('[data-lang-switch][open]').forEach(function (d) {
      d.removeAttribute('open');
    });
  });

  // --- Arrival ------------------------------------------------------------
  /* "Remember the user's preferred language for future visits."
     Deliberately conservative: we only move a visitor who has previously
     made an explicit choice, only once per tab, and never away from a URL
     they were sent to in a specific language during this session. A blanket
     Accept-Language redirect is avoided on purpose — it hides the English
     canonical from crawlers and overrides visitors who WANT the other
     edition, which is a worse failure than showing the default. */
  function maybeRedirectOnArrival() {
    var pref = readStored();
    if (!pref) return;
    var here = currentLocale();
    if (pref === here) return;
    if (pageSupportsInstant()) { switchInstant(pref); return; }
    var already = null;
    try { already = window.sessionStorage.getItem(REDIRECT_GUARD); } catch (e) { /* fine */ }
    if (already) return;
    try { window.sessionStorage.setItem(REDIRECT_GUARD, '1'); } catch (e) { /* fine */ }
    var target = I18N.resolvedPathFor(window.location.href, pref);
    if (target !== window.location.pathname + window.location.search + window.location.hash) {
      window.location.replace(target);
    }
  }

  function init() {
    var here = currentLocale();
    applyDirection(here);
    if (pageSupportsInstant()) {
      loadDict(here).then(function () {
        applyDict(here);
        renderSwitcher(here);
        maybeRedirectOnArrival();
      });
    } else {
      renderSwitcher(here);
      maybeRedirectOnArrival();
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  // Exposed so other scripts (portal dashboards rendering dynamic rows) can
  // format in the reader's language without re-deriving any of this.
  window.SHRS_LOCALE = {
    current: currentLocale,
    switchTo: switchTo,
    t: function (key, vars) { return I18N.translate(dicts, currentLocale(), key, vars); },
    formatDate: function (d, o) { return I18N.formatDate(d, currentLocale(), o); },
    formatNumber: function (n, o) { return I18N.formatNumber(n, currentLocale(), o); },
    formatCurrency: function (n, c) { return I18N.formatCurrency(n, currentLocale(), c); },
  };
})();
