#!/usr/bin/env python3
"""Builds the school's stationery — the letter, the blank sheet, and the
Word template — from sources that all live in this repository.

Run it from anywhere:  python3 brand/build.py

Everything the sheet needs is either a committed file or computed here:

  fonts   assets/fonts/*.woff2        embedded, so a PDF renders with no
  crest   assets/images/brand-mark.png  network and no installed font
  prose   brand/letter-registrar-activation.src.html
  ornament                            generated by rule, below — never a
                                      stored texture (§IV)

See docs/letterhead-editorial-bible.md; every rule below cites its section.
"""
import base64, math, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'brand'

b64 = lambda rel: base64.b64encode((ROOT / rel).read_bytes()).decode('ascii')
svg64 = lambda markup: base64.b64encode(markup.encode('utf-8')).decode('ascii')

# --- The seven faces (§VI) --------------------------------------------------
# Weights are those the sheet actually sets. Adding a rule that needs an
# eighth means adding it here too, or the PDF silently falls back.
FACES = [
    ('Cinzel', 'normal', 400, 'cinzel-latin-400-normal.woff2'),
    ('Cinzel', 'normal', 700, 'cinzel-latin-700-normal.woff2'),
    ('Cinzel', 'normal', 800, 'cinzel-latin-800-normal.woff2'),
    ('Cormorant Garamond', 'italic', 500, 'cormorant-garamond-latin-500-italic.woff2'),
    ('Cormorant Garamond', 'normal', 600, 'cormorant-garamond-latin-600-normal.woff2'),
    ('Inter', 'normal', 400, 'inter-latin-400-normal.woff2'),
    ('Inter', 'normal', 600, 'inter-latin-600-normal.woff2'),
    ('Amiri', 'normal', 400, 'amiri-arabic-400-normal.woff2'),
]
FONTS = "".join(
    "@font-face{font-family:'%s';font-style:%s;font-weight:%d;font-display:block;"
    "src:url(data:font/woff2;base64,%s) format('woff2');}"
    % (fam, style, weight, b64('assets/fonts/' + f))
    for fam, style, weight, f in FACES)

CREST = b64('assets/images/brand-mark.png')


# --- Ornament, generated by rule (§IV) --------------------------------------
# Rule-generated ornament is why banknotes look like banknotes. An ornament
# whose provenance cannot be stated is forbidden, so none of these is a file.

def guilloche(w=1400, h=40, copies=15, step=0.8):
    """Two summed sine waves, phase-shifted `copies` times — how security
    printing actually rules a lathe pattern. Four cycles of the long wave
    against nine of the short: coprime, so the interference never repeats
    across the band."""
    k1, k2 = 2 * math.pi * 4 / w, 2 * math.pi * 9 / w
    a1, a2 = 10.0, 4.2                     # amplitudes; a1 + a2 < h/2, so it never clips
    d1, d2 = 0.24, 0.456                   # phase advance per copy
    paths = []
    for i in range(copies):
        pts = ['%.2f,%.2f' % (n * step,
                              h / 2 + a1 * math.sin(k1 * n * step + d1 * i)
                                    + a2 * math.sin(k2 * n * step + d2 * i))
               for n in range(int(w / step) + 1)]
        paths.append('<path d="M' + ' L'.join(pts) + '" fill="none" '
                     'stroke="#D8B36A" stroke-width=".45" opacity=".5"/>')
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
            'preserveAspectRatio="none">%s</svg>' % (w, h, "".join(paths)))


def grain():
    """§III — fractal noise, desaturated. Below the threshold of conscious
    notice, above the threshold of feeling. Paper is never one flat value."""
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="220" height="220">'
            '<filter id="g"><feTurbulence type="fractalNoise" baseFrequency="0.9" '
            'numOctaves="4" stitchTiles="stitch"/>'
            '<feColorMatrix type="saturate" values="0"/></filter>'
            '<rect width="220" height="220" filter="url(#g)" opacity="0.42"/></svg>')


def microtext(repeats=12):
    """§IV — the school's name at ~2pt, legible only under inspection. Both
    an ornament and a genuine authenticity mark, which is why it is set in
    real text and never drawn."""
    run = ('SULTAN&#160;HANAFI&#160;ROYAL&#160;SCHOOLS&#160;&#9670;&#160;') * repeats
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 12" '
            'preserveAspectRatio="none"><text x="0" y="9" '
            'font-family="Helvetica,Arial,sans-serif" font-size="8" '
            'letter-spacing="1.4" fill="#9A7C43" opacity=".55">%s</text></svg>' % run)


BAND, GRAIN, MICRO = svg64(guilloche()), svg64(grain()), svg64(microtext())

AR = 'مدارس السلطان حنفي الملكية'          # §Rule 0 — plural, with the article
INST = ("Nursery &amp; Primary &#9670; Royal College &#9670; Islamic &amp; Arabic Studies "
        "&#9670; Qur&rsquo;an College &#9670; Online &amp; Distance Learning")

# --- Icons (§V-b) — five, and only five -------------------------------------
ic = lambda d: ('<svg class="ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
                'stroke-width="1.1" stroke-linecap="round" stroke-linejoin="round">' + d + '</svg>')
PIN  = ic('<path d="M12 21s7-6.1 7-11a7 7 0 1 0-14 0c0 4.9 7 11 7 11z"/><circle cx="12" cy="10" r="2.6"/>')
TEL  = ic('<path d="M6.2 3.5h3.1l1.6 4-2 1.4a12.5 12.5 0 0 0 6.2 6.2l1.4-2 4 1.6v3.1a1.7 1.7 0 0 1-1.8 1.7A16.8 16.8 0 0 1 4.5 5.3 1.7 1.7 0 0 1 6.2 3.5z"/>')
ENV  = ic('<rect x="2.6" y="5.4" width="18.8" height="13.2" rx="1.4"/><path d="m2.6 6.6 9.4 6.6 9.4-6.6"/>')
GLB  = ic('<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18z"/>')
SEAL = ic('<circle cx="12" cy="9.6" r="6.2"/><path d="m8.3 15.2-1.1 6 4.8-2.6 4.8 2.6-1.1-6"/><path d="m9.8 9.6 1.6 1.7 3-3.3"/>')

CSS = FONTS + """
*{margin:0;padding:0;box-sizing:border-box}
body{background:#120509;display:flex;flex-direction:column;align-items:center;gap:9mm;padding:9mm 0}
.page{position:relative;width:210mm;height:297mm;overflow:hidden;display:flex;flex-direction:column;
 color:#191014;font-family:'Inter',serif;
 background:radial-gradient(132% 86% at 62% 0%,#FFFEFD 0%,#FDFBF8 42%,#F8F3EC 78%,#F2ECE2 100%)}
.grain{position:absolute;inset:0;background:url(data:image/svg+xml;base64,GRAIN__) repeat;
 background-size:78mm 78mm;opacity:.28;mix-blend-mode:multiply;pointer-events:none}
.vig{position:absolute;inset:0;pointer-events:none;
 background:radial-gradient(116% 82% at 55% 40%,rgba(0,0,0,0) 62%,rgba(58,12,22,.06) 100%)}
.wmk{position:absolute;left:56%;top:57%;width:124mm;height:124mm;transform:translate(-50%,-50%);
 background:url(data:image/png;base64,CREST__) center/contain no-repeat;opacity:.038;pointer-events:none}

/* §V-b.1 the rail — dead margin made into a spine */
.rail{position:absolute;left:0;top:0;bottom:0;width:7mm;z-index:3;
 background:linear-gradient(180deg,#3B1420,#1B0810);display:flex;align-items:center;justify-content:center}
.rail span{writing-mode:vertical-rl;transform:rotate(180deg);font-size:5pt;letter-spacing:.44em;
 text-transform:uppercase;color:#C9A45E;white-space:nowrap}
.rail::before,.rail::after{content:'';position:absolute;left:1.6mm;right:1.6mm;height:.5pt;background:#C9A45E;opacity:.65}
.rail::before{top:9.6mm} .rail::after{bottom:9.6mm}

/* §V-b.2+3 asymmetric panel, angled edge */
.mast{position:relative;height:32mm}
.panel{position:absolute;left:7mm;top:0;width:62%;height:32mm;
 background:linear-gradient(162deg,#4A1A28 0%,#2C0E17 52%,#170710 100%);
 clip-path:polygon(0 0,100% 0,100% 86%,0 100%);
 display:flex;flex-direction:column;justify-content:center;padding:0 20mm 3mm 9.6mm}
.panel-g{position:absolute;left:0;right:0;bottom:0;height:6mm;opacity:.32;
 background:url(data:image/svg+xml;base64,BAND__) center/100% 100% no-repeat}
.wordmark{position:relative;font-family:'Cinzel',serif;font-weight:800;font-size:13pt;line-height:1.06;
 letter-spacing:.045em;text-transform:uppercase;white-space:nowrap;
 background:linear-gradient(176deg,#FDF5E2 0%,#EFD9A4 22%,#C9A45E 50%,#9A7434 72%,#F7EAC6 100%);
 -webkit-background-clip:text;background-clip:text;color:transparent;
 filter:drop-shadow(0 .3pt .2pt rgba(0,0,0,.65))}
.ar{position:relative;font-family:'Amiri',serif;font-size:10.8pt;color:#E2C68F;margin-top:1.3mm;
 direction:rtl;text-align:left}
/* §V-b.4 overlap — the one focal accent */
.disc{position:absolute;left:calc(7mm + 62% - 12.5mm);top:7.4mm;width:25mm;height:25mm;z-index:4;
 padding:1.4mm;border-radius:50%;background:radial-gradient(circle at 34% 26%,#FFFEFA 0%,#F6EFE3 100%);
 box-shadow:0 0 0 .8pt #C9A45E,0 0 0 2.2mm rgba(255,254,250,.94),0 0 0 2.5mm rgba(201,164,94,.45),
 0 1.6mm 3.4mm rgba(40,8,16,.26)}
.disc img{width:100%;height:100%;display:block}
.place{position:absolute;right:0;top:7.4mm;width:26%;padding-right:14mm;text-align:right;
 font-size:5.3pt;letter-spacing:.2em;text-transform:uppercase;color:#7A2E3E;line-height:2.3}
.place b{display:block;font-weight:600;color:#3B1420}

.strip{margin:3.2mm 14mm 0 16.6mm;padding-bottom:2.4mm;border-bottom:.5pt solid rgba(122,46,62,.32);
 display:flex;align-items:baseline;gap:4mm}
.inst{font-size:5.9pt;letter-spacing:.12em;text-transform:uppercase;color:#7A2E3E;white-space:nowrap}
.est{margin-left:auto;font-size:5.3pt;letter-spacing:.22em;text-transform:uppercase;color:#9A7434;white-space:nowrap}
.micro{margin:0 14mm 0 16.6mm;height:2.4mm;opacity:.38;
 background:url(data:image/svg+xml;base64,MICRO__) left center/100% 100% no-repeat}

.mastc{display:flex;align-items:center;gap:4mm;margin:9.6mm 14mm 0 16.6mm;padding-bottom:3.2mm;
 border-bottom:.5pt solid rgba(122,46,62,.32)}
.mastc img{width:10mm;height:10mm}
.mastc .n{font-family:'Cinzel',serif;font-weight:700;font-size:9.2pt;letter-spacing:.08em;
 text-transform:uppercase;color:#2C0E17}
.mastc .o{margin-left:auto;font-size:5.9pt;letter-spacing:.2em;text-transform:uppercase;color:#7A2E3E}

.body{position:relative;flex:1;padding:9.6mm 14mm 0 16.6mm;font-size:9.8pt;line-height:1.7;color:#191014}
.body p{margin-bottom:3.2mm;text-align:justify;hyphens:auto}
.body strong{font-weight:600}
/* §Rule 12 — the drop initial is claimed by a class, never by :first-of-type,
   which would catch the addressee block instead of the opening sentence. */
.body p.opening::first-letter{font-family:'Cinzel',serif;font-weight:700;font-size:22pt;line-height:1;
 float:left;margin:1.1mm 1.7mm 0 0;color:#7A2E3E}
.ref-line{display:flex;align-items:flex-end;gap:3mm;font-size:7.2pt;color:#7A2E3E;letter-spacing:.16em;
 text-transform:uppercase;margin-bottom:6.4mm}
.ref-line--f{justify-content:space-between;letter-spacing:.03em;text-transform:none;font-size:8.4pt;color:#4A3038}
.ref-rule{flex:1;border-bottom:.45pt solid rgba(122,46,62,.35);height:1px} .ref-rule--short{flex:0 0 44mm}
.addressee{margin-bottom:6.4mm!important;line-height:1.5;padding-left:3.2mm;border-left:1.4pt solid #C9A45E}
.subject{font-family:'Cinzel',serif;font-weight:700;font-size:10pt;letter-spacing:.05em;text-transform:uppercase;
 margin-bottom:6.4mm;line-height:1.42;padding-bottom:2.2mm;border-bottom:.5pt solid rgba(122,46,62,.4);color:#2C0E17}
.lead-in{font-family:'Cinzel',serif;font-size:8pt;letter-spacing:.15em;text-transform:uppercase;color:#7A2E3E;
 margin:6.4mm 0 3.2mm!important;text-align:left!important}
.fill{font-weight:600;color:#7A2E3E;border-bottom:.5pt solid rgba(122,46,62,.45);padding-bottom:.4mm}
.signoff{margin-top:6.4mm} .sig-space{height:16mm}
.sig-rule{width:62mm;height:.5pt;background:#C9A45E;margin-bottom:2.2mm}
.sig-name{line-height:1.55} .sig-title{font-size:8.3pt;color:#4A3038}

.foot{position:relative;margin-top:auto;padding-left:7mm}
.motto{text-align:right;padding:0 14mm 3.2mm 0;font-family:'Cormorant Garamond',serif;font-style:italic;
 font-size:11.2pt;color:#4A3038}
.foot-b{position:relative;background:linear-gradient(162deg,#2C0E17 0%,#170710 100%);
 clip-path:polygon(0 14%,100% 0,100% 100%,0 100%);padding:7.2mm 14mm 4.8mm 9.6mm}
.foot-g{position:absolute;left:0;right:0;top:0;height:6mm;opacity:.24;
 background:url(data:image/svg+xml;base64,BAND__) center/100% 100% no-repeat}
.fg{position:relative;display:flex;justify-content:space-between;gap:5mm;font-size:6.5pt;color:#EFE0C6;line-height:1.5}
.fg>div{display:flex;align-items:flex-start;gap:1.6mm;flex:1}
.ic{width:4.4mm;height:4.4mm;flex:0 0 auto;color:#C9A45E;margin-top:.4mm}
.fl{display:block;font-size:5.2pt;letter-spacing:.22em;text-transform:uppercase;color:#C9A45E;margin-bottom:.5mm}
.cipher{position:relative;margin-top:3.2mm;padding-top:2.4mm;border-top:.4pt solid rgba(201,164,94,.24);
 display:flex;align-items:center;gap:1.8mm;font-size:5.4pt;letter-spacing:.24em;color:#B08D4F;text-transform:uppercase}
@media print{body{background:none;padding:0;gap:0}.page{page-break-after:always}.page:last-child{page-break-after:auto}}
""".replace('GRAIN__', GRAIN).replace('CREST__', CREST).replace('BAND__', BAND).replace('MICRO__', MICRO)

MAST = f'''      <header class="mast">
        <div class="panel"><div class="panel-g"></div>
          <h1 class="wordmark">Sultan Hanafi Royal Schools</h1>
          <div class="ar">{AR}</div>
        </div>
        <div class="disc"><img src="data:image/png;base64,{CREST}" width="512" height="512" alt="Crest of Sultan Hanafi Royal Schools" /></div>
        <div class="place"><b>Ikorodu</b>Lagos State<b>Federal Republic of Nigeria</b></div>
      </header>
      <div class="strip"><span class="inst">{INST}</span><span class="est">Founded MMXVI</span></div>
      <div class="micro"></div>'''

# §Rule 5 — a continuation sheet carries a lighter masthead. Repeating the
# full ceremonial band on page four is what a template does, not an institution.
MASTC = f'''      <header class="mastc">
        <img src="data:image/png;base64,{CREST}" width="512" height="512" alt="" />
        <span class="n">Sultan Hanafi Royal Schools</span><span class="o">ICT Office &#9670; Continuation</span>
      </header>'''

FOOT = f'''      <footer class="foot">
        <p class="motto">&ldquo;Forming Scholars, Leaders and Guardians of Excellence.&rdquo;</p>
        <div class="foot-b"><div class="foot-g"></div>
          <div class="fg">
            <div>{PIN}<span><span class="fl">Campus</span>Ikorodu, Lagos State, Nigeria</span></div>
            <div>{TEL}<span><span class="fl">Telephone</span>+234 807 374 7650<br />+234 807 058 6860</span></div>
            <div>{ENV}<span><span class="fl">Correspondence</span>info@shroyalschools.com</span></div>
            <div>{GLB}<span><span class="fl">Online</span>shroyalschools.com</span></div>
          </div>
          <p class="cipher">{SEAL}<span>Established July 2016 &#9670; Governed by a Board of Governors &#9670; Verifiable at shroyalschools.com/verify</span></p>
        </div>
      </footer>'''


def page(inner, full=True, rail='Office of the ICT'):
    return (f'  <div class="page" data-canvas-width="794" data-canvas-height="1123">\n'
            f'    <div class="grain"></div><div class="vig"></div><div class="wmk"></div>\n'
            f'    <div class="rail"><span>{rail}</span></div>\n'
            f'{MAST if full else MASTC}\n{inner}\n{FOOT}\n  </div>')


def doc(title, pages):
    return ('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8" />\n<title>' + title +
            '</title>\n<meta name="hz:slide-selector" content=".page" />\n'
            '<meta name="hz:canvas-width" content="794" />\n<meta name="hz:canvas-height" content="1123" />\n'
            '<style>' + CSS + '</style>\n</head>\n<body>\n' + "\n".join(pages) + '\n</body>\n</html>\n')


def build():
    # §Rule 13 — the letter begins on sheet one. Pagination is declared in the
    # prose file, so re-editing a paragraph cannot silently move a page break.
    src = (OUT / 'letter-registrar-activation.src.html').read_text(encoding='utf-8')
    src = re.sub(r'<!--.*?-->', '', src, flags=re.S)          # the file's own notes
    sheets = [s.strip() for s in src.split('PAGE-BREAK') if s.strip()]
    body = lambda s: ('      <main class="body">\n'
                      + "\n".join('        ' + l for l in s.split('\n')) + '\n      </main>')
    (OUT / 'letter-registrar-activation.html').write_text(
        doc('Sultan Hanafi Royal Schools — Letter',
            [page(body(s), i == 0) for i, s in enumerate(sheets)]), encoding='utf-8')

    blank = ('      <main class="body">\n        <div class="ref-line"><span>Ref</span>'
             '<span class="ref-rule"></span><span>Date</span>'
             '<span class="ref-rule ref-rule--short"></span></div>\n      </main>')
    (OUT / 'letterhead.html').write_text(
        doc('Sultan Hanafi Royal Schools — Letterhead',
            [page(blank, True, 'Sultan Hanafi Royal Schools')]), encoding='utf-8')
    print('built: letter (%d sheets) + blank stationery' % len(sheets))
    return len(sheets)


if __name__ == '__main__':
    build()
