-- SHRS — INSTITUTION CREDENTIAL ID ASSIGNMENT
-- Generated by scripts/build-credential-ids.mjs from the published registers.
--
-- 49 certificates. 33 carry this value in their own sealed register
-- already (minted 15 Aug 2026, ICID written at issuance); for those the UPDATE
-- below changes nothing and exists to PROVE the issuance path and the
-- derivation agree. The remaining 16 predate the column and are pinned here.
--
-- The ICID is UUIDv5(stored serial, SHRS namespace) — see
-- functions/_lib/credential-id.js for why it is derived rather than random.
-- It is never printed on a certificate and never returned to the public.
--
-- SAFE TO RUN REPEATEDLY. Every value is a pure function of a serial that is
-- engraved on paper and cannot change, so a second run writes the same values.
--
-- ONE TRANSACTION, with an assertion at the end.

BEGIN;

UPDATE stage_certificates SET credential_id = 'b77b1a02-797d-552b-b5b9-f4b4aae5a25c'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000035-368DC';  -- Hameedah Adebimpe Ojewumi
UPDATE stage_certificates SET credential_id = '10bf0031-bc1b-580f-accb-ee6c69704c8c'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000036-B9E10';  -- Aisha Anofi
UPDATE stage_certificates SET credential_id = '89328af3-b756-5596-b904-75ec016a1277'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000037-22C49';  -- Abdulbasit Adedokun
UPDATE stage_certificates SET credential_id = '061b7f7d-f0ec-51cd-8ee1-afc2cef4c168'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000038-2944F';  -- Naheemah Ismail
UPDATE stage_certificates SET credential_id = '83a7321f-47ba-5abb-a22f-36afaeae1305'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000039-518A8';  -- Ashrof Akorede
UPDATE stage_certificates SET credential_id = '9d1e403d-cdc0-50aa-ac5b-a4c8c707e316'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000040-60DAF';  -- Imran Adegoke
UPDATE stage_certificates SET credential_id = '835e27e5-c7a8-5781-880f-edae9fe76201'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000041-6F66F';  -- Abdulateef Adedokun
UPDATE stage_certificates SET credential_id = 'ac106a8e-010d-5c22-b92c-867a8a99cbd2'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000048-0B67B';  -- issued live 2026-08-16 (IBT)
UPDATE stage_certificates SET credential_id = '11a6be6d-4468-5d20-ab40-2f38dace0b83'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000057-DEE3D';  -- Ameerah Abdulhafeez
UPDATE stage_certificates SET credential_id = '5bfa37ab-3bbb-590d-a344-3876fe4094cc'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000058-05F84';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = '03d051eb-a010-5f55-98d3-b53f18af5ad5'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000059-0C5E5';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '4faf90d7-6a22-5f00-8b04-63db084d9845'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000042-56798';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '0fb29e10-ecf4-5b26-b18d-ba857ccde322'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000043-6EEAF';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = 'a74ad80e-7fe9-5d15-a31a-cdb388e8b9cb'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000044-8B125';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = 'bcd05722-edb0-5aba-987f-520f3c528e17'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000045-F546F';  -- Thoirah Makinde
UPDATE stage_certificates SET credential_id = '715854e9-9744-5d26-b843-5c797d99fec0'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000046-7E37A';  -- Abdulbasit Amobi Jabarr
UPDATE stage_certificates SET credential_id = 'afa918e7-4300-586f-b52e-53525f32b08d'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000047-CB9F5';  -- Abdullah Oladimeji Anofi
UPDATE stage_certificates SET credential_id = '4d9a79fa-656b-547d-80cb-4beccb4bfd1b'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000049-0BEE7';  -- issued live 2026-08-21 (IDD)
UPDATE stage_certificates SET credential_id = '397875b2-5a77-5673-9f0a-1f9baff4293a'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000060-9051A';  -- Yaseer Balogun
UPDATE stage_certificates SET credential_id = 'e3b90834-0c54-587a-9f5a-ba5955fe92eb'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000067-B0CEA';  -- Abdulrahman Abdullah
UPDATE stage_certificates SET credential_id = 'b1eddf6d-71e3-59de-a8ea-ffff763f755f'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000068-3D224';  -- Aisha Omoshalewa Anofi
UPDATE stage_certificates SET credential_id = 'b42ac3b1-920b-533f-95d2-d74b0491dcc6'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000069-D6D81';  -- Allison Ganiyah
UPDATE stage_certificates SET credential_id = '952a18b5-3c86-5695-b8e7-01d591370eab'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000070-35EF4';  -- Ameerah Abdulhafeez
UPDATE stage_certificates SET credential_id = '5b0ffaa7-9aba-56e3-9bae-4005a8a5b781'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000071-658B5';  -- Ameerah Durodola
UPDATE stage_certificates SET credential_id = '1fde6963-2071-5053-bd74-4daa6c3b3ddf'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000072-B2F00';  -- Anisa Opeyemi Jokomba
UPDATE stage_certificates SET credential_id = 'c9f77fb6-0280-507c-95cc-9b5f01873e78'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000073-8681B';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = 'a5b97457-e3dc-52bd-a380-58eda4e84a49'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000074-3441D';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = 'c11a16aa-cc08-56d2-97c9-9ceba5b79f25'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000075-99C19';  -- Fatimah Desire Ibrahim
UPDATE stage_certificates SET credential_id = '48709d6e-74d9-5c99-8626-6317d5db5ba9'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000076-C4FF9';  -- Fawaz Owolabi
UPDATE stage_certificates SET credential_id = '4d612ea3-44c4-54db-8f9e-a0ccb8fbc249'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000077-29A2D';  -- Hameedah Adebimpe Ojewumi
UPDATE stage_certificates SET credential_id = 'e282255a-e75f-55b4-837e-c7157261ed67'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000078-91C8A';  -- Jubril Lawal
UPDATE stage_certificates SET credential_id = 'fec7e452-edcb-57f9-9f1d-890db27a134b'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000079-16768';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = 'b95b37f2-232d-543a-9fa0-ae963e5d6a48'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000080-88AB8';  -- Radiah Apatira
UPDATE stage_certificates SET credential_id = 'a0f9c251-c5d2-577e-bfbb-c05b9310f7af'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000081-969B6';  -- Sa'ad Sanusi
UPDATE stage_certificates SET credential_id = '219337e3-fbfc-53f7-81aa-c0d44dc58f11'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000061-64493';  -- Aisha Lawal
UPDATE stage_certificates SET credential_id = 'db6cae0f-eddf-550b-b23c-1cb9aa91c37f'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000062-0359E';  -- Al-ameen Okoh
UPDATE stage_certificates SET credential_id = '1900d49c-f8f2-5db7-b11d-facb1386404a'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000063-D9951';  -- Ashraf Korede Ojewumi
UPDATE stage_certificates SET credential_id = '340a7441-68a4-5c35-bc9f-e6d7b843c34b'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000064-2C831';  -- Daud Aliu
UPDATE stage_certificates SET credential_id = '1acbd84e-9059-5065-88db-fb6500c481f7'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000065-5E4DD';  -- Imran Iremide Adegoke
UPDATE stage_certificates SET credential_id = '0241c392-4684-54f1-9e11-5c2eea5dea85'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000066-DA467';  -- Naheemah Ismail
UPDATE stage_certificates SET credential_id = '01c0500b-3410-5166-91d4-e3a88aed1b86'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000053-1ADE9';  -- Aisha Omoshalewa Anofi
UPDATE stage_certificates SET credential_id = '8492a16f-6d55-549b-bcb7-a707cfaa39a0'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000054-FC895';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = '65d14162-3e21-5042-a95f-50885175515e'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000055-D7E3F';  -- Zaynab Zakariya Anofi
UPDATE stage_certificates SET credential_id = '2fdad197-eb9f-5c37-91a6-5bb859d4e978'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000082-0F4C1';  -- Abdulbasit Amobi Jabarr
UPDATE stage_certificates SET credential_id = 'e7fd4be3-89de-59a0-acac-7199d78b4166'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000083-4721C';  -- Aisha Shode
UPDATE stage_certificates SET credential_id = 'ff70bae5-aa40-5142-a04b-66aa53a0794e'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000084-3CF47';  -- Mazeed Hassan-Murtala
UPDATE stage_certificates SET credential_id = '7d0e5c48-92a9-5420-a60c-0e8a7880b408'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000085-155CE';  -- Thoirah Makinde
UPDATE stage_certificates SET credential_id = 'bc413496-9c7c-5bc2-8bab-3a61b5477fe5'::uuid
  WHERE serial_no = 'SHRS-CERT-THN-2026-000050-62EEC';  -- issued live 2026-08-21 (THN)
UPDATE stage_certificates SET credential_id = 'a96eff19-8f27-578c-8c98-3ae3cea3d15a'::uuid
  WHERE serial_no = 'SHRS-CERT-TMH-2026-000056-8DD83';  -- Abdulbasit Adedokun

-- ─────────────────────────────────────────────────────────────────────────
-- THE ASSERTION. Two ways this could go wrong quietly, both checked:
--
--   1. A certificate on file carries an ICID that is NOT in the list above —
--      meaning it is still holding the database-generated default, and the
--      permanent identifier is an accident of which environment inserted it.
--   2. Two certificates share one. UNIQUE would already have refused the
--      write, but reporting it here names the pair instead of raising 23505.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  stray text;
  n    int;
BEGIN
  SELECT string_agg(serial_no, E'\n    '), count(*) INTO stray, n
  FROM stage_certificates
  WHERE credential_id NOT IN (
    'b77b1a02-797d-552b-b5b9-f4b4aae5a25c'::uuid,
    '10bf0031-bc1b-580f-accb-ee6c69704c8c'::uuid,
    '89328af3-b756-5596-b904-75ec016a1277'::uuid,
    '061b7f7d-f0ec-51cd-8ee1-afc2cef4c168'::uuid,
    '83a7321f-47ba-5abb-a22f-36afaeae1305'::uuid,
    '9d1e403d-cdc0-50aa-ac5b-a4c8c707e316'::uuid,
    '835e27e5-c7a8-5781-880f-edae9fe76201'::uuid,
    'ac106a8e-010d-5c22-b92c-867a8a99cbd2'::uuid,
    '11a6be6d-4468-5d20-ab40-2f38dace0b83'::uuid,
    '5bfa37ab-3bbb-590d-a344-3876fe4094cc'::uuid,
    '03d051eb-a010-5f55-98d3-b53f18af5ad5'::uuid,
    '4faf90d7-6a22-5f00-8b04-63db084d9845'::uuid,
    '0fb29e10-ecf4-5b26-b18d-ba857ccde322'::uuid,
    'a74ad80e-7fe9-5d15-a31a-cdb388e8b9cb'::uuid,
    'bcd05722-edb0-5aba-987f-520f3c528e17'::uuid,
    '715854e9-9744-5d26-b843-5c797d99fec0'::uuid,
    'afa918e7-4300-586f-b52e-53525f32b08d'::uuid,
    '4d9a79fa-656b-547d-80cb-4beccb4bfd1b'::uuid,
    '397875b2-5a77-5673-9f0a-1f9baff4293a'::uuid,
    'e3b90834-0c54-587a-9f5a-ba5955fe92eb'::uuid,
    'b1eddf6d-71e3-59de-a8ea-ffff763f755f'::uuid,
    'b42ac3b1-920b-533f-95d2-d74b0491dcc6'::uuid,
    '952a18b5-3c86-5695-b8e7-01d591370eab'::uuid,
    '5b0ffaa7-9aba-56e3-9bae-4005a8a5b781'::uuid,
    '1fde6963-2071-5053-bd74-4daa6c3b3ddf'::uuid,
    'c9f77fb6-0280-507c-95cc-9b5f01873e78'::uuid,
    'a5b97457-e3dc-52bd-a380-58eda4e84a49'::uuid,
    'c11a16aa-cc08-56d2-97c9-9ceba5b79f25'::uuid,
    '48709d6e-74d9-5c99-8626-6317d5db5ba9'::uuid,
    '4d612ea3-44c4-54db-8f9e-a0ccb8fbc249'::uuid,
    'e282255a-e75f-55b4-837e-c7157261ed67'::uuid,
    'fec7e452-edcb-57f9-9f1d-890db27a134b'::uuid,
    'b95b37f2-232d-543a-9fa0-ae963e5d6a48'::uuid,
    'a0f9c251-c5d2-577e-bfbb-c05b9310f7af'::uuid,
    '219337e3-fbfc-53f7-81aa-c0d44dc58f11'::uuid,
    'db6cae0f-eddf-550b-b23c-1cb9aa91c37f'::uuid,
    '1900d49c-f8f2-5db7-b11d-facb1386404a'::uuid,
    '340a7441-68a4-5c35-bc9f-e6d7b843c34b'::uuid,
    '1acbd84e-9059-5065-88db-fb6500c481f7'::uuid,
    '0241c392-4684-54f1-9e11-5c2eea5dea85'::uuid,
    '01c0500b-3410-5166-91d4-e3a88aed1b86'::uuid,
    '8492a16f-6d55-549b-bcb7-a707cfaa39a0'::uuid,
    '65d14162-3e21-5042-a95f-50885175515e'::uuid,
    '2fdad197-eb9f-5c37-91a6-5bb859d4e978'::uuid,
    'e7fd4be3-89de-59a0-acac-7199d78b4166'::uuid,
    'ff70bae5-aa40-5142-a04b-66aa53a0794e'::uuid,
    '7d0e5c48-92a9-5420-a60c-0e8a7880b408'::uuid,
    'bc413496-9c7c-5bc2-8bab-3a61b5477fe5'::uuid,
    'a96eff19-8f27-578c-8c98-3ae3cea3d15a'::uuid
  );
  IF n > 0 THEN
    RAISE EXCEPTION E'ABORTED — % certificate(s) still carry a database-generated ICID rather than their derived one:\n    %', n, stray;
  END IF;
END $$;

SELECT 'credential ids assigned' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'distinct credential ids', count(DISTINCT credential_id)::text FROM stage_certificates;

COMMIT;
