-- SHRS GRADUATION REGISTER — PRODUCTION IMPORT
-- Generated by scripts/build-production-import.mjs from the sealed registers:
--     docs/graduation-registers/2026-08-08-IBT-000035.sql
--     docs/graduation-registers/2026-08-08-IDD-000042.sql
--
-- 13 certificates, already issued, already printed, already handed to
-- the graduands. This file creates their RECORDS. It changes nothing about
-- the documents and cannot: every INSERT below is a verbatim copy of the
-- sealed register's own statement, and the generator asserts that copy is
-- exact before writing. No identifier and no cryptographic field is
-- recomputed anywhere in this file.
--
-- SAFE TO RUN TWICE. Every insert carries ON CONFLICT DO NOTHING and the
-- sequence repairs can only move a counter forward, so a second execution
-- leaves the database byte-for-byte unchanged.
--
-- ONE TRANSACTION. If any check at the end fails, the whole import rolls
-- back and the database is exactly as it was. A half-imported cohort is the
-- one state harder to recover from than no import at all.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────
-- 0. BEFORE-STATE. Read, never assume. These rows are informational and are
--    printed by psql as the transaction runs, so the operator can see what
--    production actually held before anything was written.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'BEFORE  certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'BEFORE  highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'BEFORE  serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'BEFORE  student id sequence stands at', last_value::text FROM student_identity_seq;

-- ─────────────────────────────────────────────────────────────────────────
-- 1. PERMANENT STUDENT IDs, attached to the children who already hold them.
--    Guarded by identity_no IS NULL: a student who already carries an ID is
--    never overwritten, which makes these idempotent AND makes them refuse
--    to silently change a number that is printed on a document. A student
--    row that does not exist matches nothing and reports UPDATE 0 — the
--    certificate still verifies, because the certificate row carries the ID
--    itself; the child's record is simply not yet linked, and §5 lists it.
-- ─────────────────────────────────────────────────────────────────────────
UPDATE students SET identity_no = '714743483445443' WHERE full_name = 'Hameedah Adebimpe Ojewumi' AND identity_no IS NULL;
UPDATE students SET identity_no = '717988020633236' WHERE full_name = 'Aisha Anofi' AND identity_no IS NULL;
UPDATE students SET identity_no = '711232557821021' WHERE full_name = 'Abdulbasit Adedokun' AND identity_no IS NULL;
UPDATE students SET identity_no = '714477095008816' WHERE full_name = 'Naheemah Ismail' AND identity_no IS NULL;
UPDATE students SET identity_no = '717721632196601' WHERE full_name = 'Ashrof Akorede' AND identity_no IS NULL;
UPDATE students SET identity_no = '710966169384396' WHERE full_name = 'Imran Adegoke' AND identity_no IS NULL;
UPDATE students SET identity_no = '714210706572189' WHERE full_name = 'Abdulateef Adedokun' AND identity_no IS NULL;
UPDATE students SET identity_no = '717455243759974' WHERE full_name = 'Muhammad Ismail Seriki' AND identity_no IS NULL;
UPDATE students SET identity_no = '710699780947768' WHERE full_name = 'Baqi Olamiposi Anofi' AND identity_no IS NULL;
UPDATE students SET identity_no = '713944318135552' WHERE full_name = 'Faridah Ayomide Aliu' AND identity_no IS NULL;
UPDATE students SET identity_no = '717188855323348' WHERE full_name = 'Thoirah Makinde' AND identity_no IS NULL;
UPDATE students SET identity_no = '710433392511139' WHERE full_name = 'Abdulbasit Amobi Jabarr' AND identity_no IS NULL;
UPDATE students SET identity_no = '713677929698929' WHERE full_name = 'Abdullah Oladimeji Anofi' AND identity_no IS NULL;

-- ─────────────────────────────────────────────────────────────────────────
-- 2. THE CERTIFICATES. Verbatim from the sealed registers. The only edit is
--    the conflict clause.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (35, 'SHRS-CERT-IBT-2026-000035-368DC', '714743483445443', 'Hameedah Adebimpe Ojewumi', 'حميدة أدبيمبي أوجومي', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '368dcfc6b85d292928dc961ffaf9fc5e2f010e2c77bb51efe96700c1e0f55c2a')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (36, 'SHRS-CERT-IBT-2026-000036-B9E10', '717988020633236', 'Aisha Anofi', 'عائشة حنفي', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'b9e10eaf65e69aafc03b73f12267a87046778208e857c720a1c275d039a4a7e9')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (37, 'SHRS-CERT-IBT-2026-000037-22C49', '711232557821021', 'Abdulbasit Adedokun', 'عبد الباسط أددوكن', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '22c4933df6f5888a0bfda2bf9d8650b345c2565755290ed50ddc6eefa93f6392')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (38, 'SHRS-CERT-IBT-2026-000038-2944F', '714477095008816', 'Naheemah Ismail', 'نعيمة إسماعيل', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '2944f25ab89a79dab78b4aa5d536eeb7288afa15ce372d336f37809eaa9405ce')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (39, 'SHRS-CERT-IBT-2026-000039-518A8', '717721632196601', 'Ashrof Akorede', 'أشرف أكوردي', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '518a886ac51546922006ad4f507638400ab558b9a3926314f723f7142f59eb99')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (40, 'SHRS-CERT-IBT-2026-000040-60DAF', '710966169384396', 'Imran Adegoke', 'عمران أدغكي', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '60daf10c4deafc4518cab95c61b5ea2dcb584152318dddd1388644430cb6f923')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash) VALUES (41, 'SHRS-CERT-IBT-2026-000041-6F66F', '714210706572189', 'Abdulateef Adedokun', 'عبد اللطيف أددوكن', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '6f66f5435e5737d63886f66142275693c8b2089aa8577ad6e56a389c63ce1103')
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (42, 'SHRS-CERT-IDD-2026-000042-56798', '717455243759974', 'Muhammad Ismail Seriki', 'محمد إسماعيل سركي', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '567985893c87a55b2c3725add799b7461f19825a5a830ba874e74ff9495cab70', 2)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (43, 'SHRS-CERT-IDD-2026-000043-6EEAF', '710699780947768', 'Baqi Olamiposi Anofi', 'باقي أولاميبوسي حنفي', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '6eeafeda366645ca99755a1198d5d938c453638587b13a20cef52f3b7bf00999', 2)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (44, 'SHRS-CERT-IDD-2026-000044-8B125', '713944318135552', 'Faridah Ayomide Aliu', 'فريدة أيومدي علي', 'female', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '8b125e6ff74814d640e051884678a1f4b55c8366a2172c308b368f6889352e94', 2)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (45, 'SHRS-CERT-IDD-2026-000045-F546F', '717188855323348', 'Thoirah Makinde', 'طاهرة مكيندي', 'female', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'f546f2d29269ef7ac03a9b2b833924785bee3e39e9a2247a9a7373a5a99eb0e1', 2)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (46, 'SHRS-CERT-IDD-2026-000046-7E37A', '710433392511139', 'Abdulbasit Amobi Jabarr', 'عبد الباسط أموبي جبار', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '7e37aa8660cf5764f4ad48844ccaeb47fb2b299961b773da3fe6755e45f1a049', 2)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (47, 'SHRS-CERT-IDD-2026-000047-CB9F5', '713677929698929', 'Abdullah Oladimeji Anofi', 'عبد الله أولاديميجي حنفي', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'cb9f5e12f5df45df8c896afec6f770772d4bde5985c08f216b5efaa9dd8ca954', 2)
  ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- 3. THE NUMBERING, PROTECTED.
--
--    The engraved number comes from stage_certificate_serial_seq. After this
--    import it must stand at 47, so the next certificate the Registrar
--    issues is 000048 — never 000042 again, which is engraved on a
--    document in a child's hands.
--
--    GREATEST, not a bare setval, for two reasons. It is order-independent,
--    so importing these batches in either order lands in the same place. And
--    it can only move the counter FORWARD: if production has somehow already
--    issued beyond 47, this will not wind it back on top of that work.
--    The value is read from the table, not assumed.
-- ─────────────────────────────────────────────────────────────────────────
SELECT setval('stage_certificate_serial_seq', GREATEST(
  (SELECT COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1]::int), 0) FROM stage_certificates),
  (SELECT last_value FROM stage_certificate_serial_seq)
), true);

--    stage_certificates.id has its own SERIAL sequence, and an INSERT that
--    supplies id explicitly does NOT advance it. Leaving it behind is a
--    silent fault, not a loud one: the next certificate inserts cleanly with
--    id 1, and because the archive reference and the Code 128 payload both
--    derive from cert.id while the engraved number derives from the serial
--    sequence, that certificate would print a barcode naming a different
--    record than its own number.
SELECT setval(pg_get_serial_sequence('stage_certificates', 'id'), GREATEST(
  (SELECT COALESCE(MAX(id), 0) FROM stage_certificates),
  47
), true);

--    The permanent Student ID counter, same discipline. These IDs are for
--    life; re-issuing one to a different child is unrecoverable.
SELECT setval('student_identity_seq', GREATEST(
  (SELECT last_value FROM student_identity_seq), 47
), true);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. THE CHECK THAT MAKES ON CONFLICT DO NOTHING HONEST.
--
--    DO NOTHING is exactly right for re-running an import, and exactly wrong
--    if left unchecked: it will also swallow a genuine collision — a row
--    already occupying one of these ids, or a serial typed in by hand with
--    different content — and report success. So every certificate is read
--    back and compared against what is engraved on the sheet. Serial alone
--    is not enough; the content hash, the printed name and the Student ID
--    are compared too, because a record that merely has the right number
--    while disagreeing about the child is worse than no record.
--
--    Any mismatch raises and the entire transaction rolls back.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  bad text;
  n   int;
BEGIN
  WITH issued(serial_no, content_hash, student_identity_no, student_full_name) AS (VALUES
    ('SHRS-CERT-IBT-2026-000035-368DC', '368dcfc6b85d292928dc961ffaf9fc5e2f010e2c77bb51efe96700c1e0f55c2a', '714743483445443', 'Hameedah Adebimpe Ojewumi'),
    ('SHRS-CERT-IBT-2026-000036-B9E10', 'b9e10eaf65e69aafc03b73f12267a87046778208e857c720a1c275d039a4a7e9', '717988020633236', 'Aisha Anofi'),
    ('SHRS-CERT-IBT-2026-000037-22C49', '22c4933df6f5888a0bfda2bf9d8650b345c2565755290ed50ddc6eefa93f6392', '711232557821021', 'Abdulbasit Adedokun'),
    ('SHRS-CERT-IBT-2026-000038-2944F', '2944f25ab89a79dab78b4aa5d536eeb7288afa15ce372d336f37809eaa9405ce', '714477095008816', 'Naheemah Ismail'),
    ('SHRS-CERT-IBT-2026-000039-518A8', '518a886ac51546922006ad4f507638400ab558b9a3926314f723f7142f59eb99', '717721632196601', 'Ashrof Akorede'),
    ('SHRS-CERT-IBT-2026-000040-60DAF', '60daf10c4deafc4518cab95c61b5ea2dcb584152318dddd1388644430cb6f923', '710966169384396', 'Imran Adegoke'),
    ('SHRS-CERT-IBT-2026-000041-6F66F', '6f66f5435e5737d63886f66142275693c8b2089aa8577ad6e56a389c63ce1103', '714210706572189', 'Abdulateef Adedokun'),
    ('SHRS-CERT-IDD-2026-000042-56798', '567985893c87a55b2c3725add799b7461f19825a5a830ba874e74ff9495cab70', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-IDD-2026-000043-6EEAF', '6eeafeda366645ca99755a1198d5d938c453638587b13a20cef52f3b7bf00999', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-IDD-2026-000044-8B125', '8b125e6ff74814d640e051884678a1f4b55c8366a2172c308b368f6889352e94', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-IDD-2026-000045-F546F', 'f546f2d29269ef7ac03a9b2b833924785bee3e39e9a2247a9a7373a5a99eb0e1', '717188855323348', 'Thoirah Makinde'),
    ('SHRS-CERT-IDD-2026-000046-7E37A', '7e37aa8660cf5764f4ad48844ccaeb47fb2b299961b773da3fe6755e45f1a049', '710433392511139', 'Abdulbasit Amobi Jabarr'),
    ('SHRS-CERT-IDD-2026-000047-CB9F5', 'cb9f5e12f5df45df8c896afec6f770772d4bde5985c08f216b5efaa9dd8ca954', '713677929698929', 'Abdullah Oladimeji Anofi')
  )
  SELECT string_agg(issued.serial_no || ' — ' || reason, E'\n    '), count(*)
    INTO bad, n
  FROM issued
  CROSS JOIN LATERAL (
    SELECT CASE
      WHEN c.id IS NULL THEN 'no record on file after import'
      WHEN lower(c.content_hash) IS DISTINCT FROM lower(issued.content_hash)
        THEN 'record content hash disagrees with the certificate'
      WHEN c.student_full_name IS DISTINCT FROM issued.student_full_name
        THEN 'record names ' || COALESCE(c.student_full_name, '(null)')
             || ', certificate names ' || issued.student_full_name
      WHEN c.student_identity_no IS DISTINCT FROM issued.student_identity_no
        THEN 'record Student ID disagrees with the certificate'
    END AS reason
    FROM (SELECT 1) _
    LEFT JOIN stage_certificates c ON c.serial_no = issued.serial_no
  ) chk
  WHERE chk.reason IS NOT NULL;

  IF n > 0 THEN
    RAISE EXCEPTION E'IMPORT ABORTED — % certificate(s) do not agree with the issued documents:\n    %', n, bad;
  END IF;

  IF (SELECT last_value FROM stage_certificate_serial_seq) < 47 THEN
    RAISE EXCEPTION 'IMPORT ABORTED — serial sequence stands at %, below the highest issued number 47. The next certificate would re-use a printed number.',
      (SELECT last_value FROM stage_certificate_serial_seq);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- 5. AFTER-STATE, and the one thing that legitimately needs a human.
--    Any child listed under "student record not linked" holds a valid
--    certificate that verifies correctly; their row in students is simply
--    missing or filed under a different spelling. Give the list to the
--    Registrar's Office. Do not edit this file to force a match.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'AFTER   certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'AFTER   highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'AFTER   serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   next certificate will be', (last_value + 1)::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   student id sequence stands at', last_value::text FROM student_identity_seq;

SELECT 'student record not linked' AS check, c.student_full_name AS value
FROM stage_certificates c
WHERE c.serial_no IN ('SHRS-CERT-IBT-2026-000035-368DC', 'SHRS-CERT-IBT-2026-000036-B9E10', 'SHRS-CERT-IBT-2026-000037-22C49', 'SHRS-CERT-IBT-2026-000038-2944F', 'SHRS-CERT-IBT-2026-000039-518A8', 'SHRS-CERT-IBT-2026-000040-60DAF', 'SHRS-CERT-IBT-2026-000041-6F66F', 'SHRS-CERT-IDD-2026-000042-56798', 'SHRS-CERT-IDD-2026-000043-6EEAF', 'SHRS-CERT-IDD-2026-000044-8B125', 'SHRS-CERT-IDD-2026-000045-F546F', 'SHRS-CERT-IDD-2026-000046-7E37A', 'SHRS-CERT-IDD-2026-000047-CB9F5')
  AND NOT EXISTS (
    SELECT 1 FROM students s WHERE s.identity_no = c.student_identity_no
  )
ORDER BY 2;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- NOT FINISHED HERE. A successful import is not a working verification page.
-- Prove it against the real public endpoint before telling anyone it is
-- fixed, and before any further sheet is released:
--
--     node scripts/verify-issued-certificates-live.mjs --full
-- ─────────────────────────────────────────────────────────────────────────
