-- SHRS GRADUATION REGISTER — PRODUCTION IMPORT
-- Generated by scripts/build-production-import.mjs from the sealed registers:
--     docs/graduation-registers/2026-08-08-QUR-000053.sql
--     docs/graduation-registers/2026-08-08-TMH-000056.sql
--     docs/graduation-registers/2026-08-08-IBT-000057.sql
--     docs/graduation-registers/2026-08-08-IDD-000060.sql
--     docs/graduation-registers/2026-08-08-PRY-000061.sql
--     docs/graduation-registers/2026-08-08-JSS-000067.sql
--     docs/graduation-registers/2026-08-08-SS-000082.sql
--
-- 33 certificates, minted on 15 August 2026 under key version 3 for the
-- graduands of the 8 August ceremony who had no certificate record at all.
-- Their numbers, names, Student IDs and content hashes are fixed the moment
-- they are minted, because the five characters engraved on the face are the
-- head of the content hash. This file creates their RECORDS. It changes nothing about
-- the documents and cannot: every INSERT below is a verbatim copy of the
-- sealed register's own statement, and the generator asserts that copy is
-- exact before writing. No identifier and no cryptographic field is
-- recomputed anywhere in this file.
--
-- SAFE TO RUN TWICE. Every insert carries ON CONFLICT DO NOTHING and the
-- sequence repairs can only move a counter forward, so a second execution
-- leaves the database byte-for-byte unchanged.
--
-- ONE TRANSACTION. If any check at the end fails, the whole import rolls
-- back and the database is exactly as it was. A half-imported cohort is the
-- one state harder to recover from than no import at all.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────
-- 0. BEFORE-STATE. Read, never assume. These rows are informational and are
--    printed by psql as the transaction runs, so the operator can see what
--    production actually held before anything was written.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'BEFORE  certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'BEFORE  highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'BEFORE  serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'BEFORE  student id sequence stands at', last_value::text FROM student_identity_seq;

-- ─────────────────────────────────────────────────────────────────────────
-- 1. PERMANENT STUDENT IDs, attached to the children who already hold them.
--    Guarded by identity_no IS NULL: a student who already carries an ID is
--    never overwritten, which makes these idempotent AND makes them refuse
--    to silently change a number that is printed on a document. A student
--    row that does not exist matches nothing and reports UPDATE 0 — the
--    certificate still verifies, because the certificate row carries the ID
--    itself; the child's record is simply not yet linked, and §5 lists it.
-- ─────────────────────────────────────────────────────────────────────────
UPDATE students SET identity_no = '711232557821021' WHERE full_name = 'Abdulbasit Adedokun' AND identity_no IS NULL;
UPDATE students SET identity_no = '719900615637876' WHERE full_name = 'Ameerah Abdulhafeez' AND identity_no IS NULL;
UPDATE students SET identity_no = '713944318135552' WHERE full_name = 'Faridah Ayomide Aliu' AND identity_no IS NULL;
UPDATE students SET identity_no = '717455243759974' WHERE full_name = 'Muhammad Ismail Seriki' AND identity_no IS NULL;
UPDATE students SET identity_no = '713145152825668' WHERE full_name = 'Yaseer Balogun' AND identity_no IS NULL;

-- ─────────────────────────────────────────────────────────────────────────
-- 2. THE CERTIFICATES. Verbatim from the sealed registers. The only edit is
--    the conflict clause.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (53, '01c0500b-3410-5166-91d4-e3a88aed1b86', 'SHRS-CERT-QUR-2026-000053-1ADE9', '717988020633236', 'Aisha Omoshalewa Anofi', 'female', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '1ade9bd8950c1b9324591e95491407cfecad1c8d8d88316418765dd1faa85c60', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (54, '8492a16f-6d55-549b-bcb7-a707cfaa39a0', 'SHRS-CERT-QUR-2026-000054-FC895', '710699780947768', 'Baqi Olamiposi Anofi', 'male', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'fc895519391ab1ba4b63cfb6081e421ea00e4ae2945f1f9f786f2e75c3922d4b', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (55, '65d14162-3e21-5042-a95f-50885175515e', 'SHRS-CERT-QUR-2026-000055-D7E3F', '716656078450081', 'Zaynab Zakariya Anofi', 'female', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'd7e3fd84b322195dc6e7d736da7e3e1f92fe868d19c2f5e108a95fec362e17fd', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (56, 'a96eff19-8f27-578c-8c98-3ae3cea3d15a', 'SHRS-CERT-TMH-2026-000056-8DD83', '711232557821021', 'Abdulbasit Adedokun', 'عبد الباسط أددوكن', 'male', 'TMH', 'Tamhīdiyyah — Preparatory Stage', 'المرحلة التمهيدية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '8dd83efd591de4c472c732f970ce7e697cca579a188201a3da3a0742ec124a60', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (57, '11a6be6d-4468-5d20-ab40-2f38dace0b83', 'SHRS-CERT-IBT-2026-000057-DEE3D', '719900615637876', 'Ameerah Abdulhafeez', 'أميرة عبد الحفيظ', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'dee3d8b43fd2a5b868bab9a5bd0e10e277d6642cf9668f3ca8d594b438828ba0', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (58, '5bfa37ab-3bbb-590d-a344-3876fe4094cc', 'SHRS-CERT-IBT-2026-000058-05F84', '713944318135552', 'Faridah Ayomide Aliu', 'فريدة أيومدي علي', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '05f84deb2e4ea8d96e43a1f5ee753573fd372b343ef1f94004c5e97798de49df', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (59, '03d051eb-a010-5f55-98d3-b53f18af5ad5', 'SHRS-CERT-IBT-2026-000059-0C5E5', '717455243759974', 'Muhammad Ismail Seriki', 'محمد إسماعيل سركي', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '0c5e5e2663927fcb5ab3f03059bbda2860aad3d86e9d869e6c02540e2f1f84b1', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (60, '397875b2-5a77-5673-9f0a-1f9baff4293a', 'SHRS-CERT-IDD-2026-000060-9051A', '713145152825668', 'Yaseer Balogun', 'ياسر بالوغون', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '9051ad852be630c3cd7d0490504bc55cb594510db3cd1c9b379fdde276772706', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (61, '219337e3-fbfc-53f7-81aa-c0d44dc58f11', 'SHRS-CERT-PRY-2026-000061-64493', '716389690013455', 'Aisha Lawal', 'female', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '6449385db0cfa54ccfb3dae9e6c842be0770638556df6bd0a307365eab9206d2', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (62, 'db6cae0f-eddf-550b-b23c-1cb9aa91c37f', 'SHRS-CERT-PRY-2026-000062-0359E', '719634227201249', 'Al-ameen Okoh', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '0359e5a21d8b20f2786e13d4bdfce3a4fa6999309cdd98ad58849a627a22cf5b', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (63, '1900d49c-f8f2-5db7-b11d-facb1386404a', 'SHRS-CERT-PRY-2026-000063-D9951', '717721632196601', 'Ashraf Korede Ojewumi', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'd99513ea989835bcb38a26044fe86d9c1e0e0709e3f5927139a2f72663a5c1ef', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (64, '340a7441-68a4-5c35-bc9f-e6d7b843c34b', 'SHRS-CERT-PRY-2026-000064-2C831', '712878764389035', 'Daud Aliu', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '2c831113a098a2935540ac5102a1913fbbd3eddc483f758b766dfa3b06c83213', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (65, '1acbd84e-9059-5065-88db-fb6500c481f7', 'SHRS-CERT-PRY-2026-000065-5E4DD', '710966169384396', 'Imran Iremide Adegoke', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '5e4dd38dc4622c9cdacc3e7720fb53f39b5f9455e2ebaa1b9d813f55e9dc395d', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (66, '0241c392-4684-54f1-9e11-5c2eea5dea85', 'SHRS-CERT-PRY-2026-000066-DA467', '714477095008816', 'Naheemah Ismail', 'female', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'da467e5fbda3c50a89d0f5987e453dc2551a259233a2b7e8999cb89758a7e0b9', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (67, 'e3b90834-0c54-587a-9f5a-ba5955fe92eb', 'SHRS-CERT-JSS-2026-000067-B0CEA', '716123301576828', 'Abdulrahman Abdullah', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'b0cea79f7dfa7c92358a8f3039a03db246310527cb596046df584d46ac9f4757', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (68, 'b1eddf6d-71e3-59de-a8ea-ffff763f755f', 'SHRS-CERT-JSS-2026-000068-3D224', '717988020633236', 'Aisha Omoshalewa Anofi', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '3d224d8a8b9b6ee2e3e041dd41be59d35d6fa8c573b181c6531a619953e8387d', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (69, 'b42ac3b1-920b-533f-95d2-d74b0491dcc6', 'SHRS-CERT-JSS-2026-000069-D6D81', '719367838764616', 'Allison Ganiyah', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'd6d810dff0453b217a38cebe5177845aa100aca045a73cd6092e6799f1c4acbb', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (70, '952a18b5-3c86-5695-b8e7-01d591370eab', 'SHRS-CERT-JSS-2026-000070-35EF4', '719900615637876', 'Ameerah Abdulhafeez', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '35ef45f6a4451a47a6a7490d8bc36d41f311a3aa7666112fd7e06f162e98f52e', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (71, '5b0ffaa7-9aba-56e3-9bae-4005a8a5b781', 'SHRS-CERT-JSS-2026-000071-658B5', '712612375952406', 'Ameerah Durodola', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '658b52a03044f84a40a30fc51b6780f4a82d08afadcc142119b207d8b37e9f62', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (72, '1fde6963-2071-5053-bd74-4daa6c3b3ddf', 'SHRS-CERT-JSS-2026-000072-B2F00', '715856913140191', 'Anisa Opeyemi Jokomba', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'b2f00be68d82fc089a448fd7479164c2da2b36f1bf64abd70554f87d9f065a2c', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (73, 'c9f77fb6-0280-507c-95cc-9b5f01873e78', 'SHRS-CERT-JSS-2026-000073-8681B', '710699780947768', 'Baqi Olamiposi Anofi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '8681bac10da5382857676e17dd306adc1bd6bf17d3a76c7bbd0afb9f56de35ba', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (74, 'a5b97457-e3dc-52bd-a380-58eda4e84a49', 'SHRS-CERT-JSS-2026-000074-3441D', '713944318135552', 'Faridah Ayomide Aliu', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '3441db123522675ffc16f2a7a6182eb390a11dce8e6168b49f06c948ca3bd4ce', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (75, 'c11a16aa-cc08-56d2-97c9-9ceba5b79f25', 'SHRS-CERT-JSS-2026-000075-99C19', '719101450327984', 'Fatimah Desire Ibrahim', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '99c195ca321f7bb9af20559ef8ec3064138b42fe9abffda8e41571d5c968a418', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (76, '48709d6e-74d9-5c99-8626-6317d5db5ba9', 'SHRS-CERT-JSS-2026-000076-C4FF9', '712345987515770', 'Fawaz Owolabi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'c4ff9f1f46da06afac0dfa5dc6a987a456fe681cd91c4a78f1ae365181721cdc', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (77, '4d612ea3-44c4-54db-8f9e-a0ccb8fbc249', 'SHRS-CERT-JSS-2026-000077-29A2D', '714743483445443', 'Hameedah Adebimpe Ojewumi', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '29a2dc9c7c94e8ca4e709c3365ec1b56e757abfb0c11e8f458052c4d06b717d4', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (78, 'e282255a-e75f-55b4-837e-c7157261ed67', 'SHRS-CERT-JSS-2026-000078-91C8A', '715590524703564', 'Jubril Lawal', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '91c8a522c1ff8c849349da471429716669a1e8afba212dee649b89412209dbcc', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (79, 'fec7e452-edcb-57f9-9f1d-890db27a134b', 'SHRS-CERT-JSS-2026-000079-16768', '717455243759974', 'Muhammad Ismail Seriki', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '1676894a253c6795adc61d54c7774308ec337de30d455034fcc96873a90b7dfb', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (80, 'b95b37f2-232d-543a-9fa0-ae963e5d6a48', 'SHRS-CERT-JSS-2026-000080-88AB8', '718835061891356', 'Radiah Apatira', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '88ab8d41a82ac0f5f1fbbb3020d57faade29fd6b7b6206420d8dc4ae1d7e6a66', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (81, 'a0f9c251-c5d2-577e-bfbb-c05b9310f7af', 'SHRS-CERT-JSS-2026-000081-969B6', '712079599079145', 'Sa''ad Sanusi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '969b6ba0f38960a9f05feac591792f7073808b3fcdc44ff4280b37accc0431d7', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (82, '2fdad197-eb9f-5c37-91a6-5bb859d4e978', 'SHRS-CERT-SS-2026-000082-0F4C1', '710433392511139', 'Abdulbasit Amobi Jabarr', 'male', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '0f4c191cef9f2f5915095f93afd515e87af3a0e3259f22e39a8a93010ea66430', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (83, 'e7fd4be3-89de-59a0-acac-7199d78b4166', 'SHRS-CERT-SS-2026-000083-4721C', '715324136266939', 'Aisha Shode', 'female', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '4721cf58716f6cde94c5d9eb749adcdd607ed762f321647edf99b39f583c8cd8', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (84, 'ff70bae5-aa40-5142-a04b-66aa53a0794e', 'SHRS-CERT-SS-2026-000084-3CF47', '718568673454723', 'Mazeed Hassan-Murtala', 'male', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '3cf4765f35cf7ce0f488aff5cd515e31c021956a69df309a9f8123afdd30b2b7', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (85, '7d0e5c48-92a9-5420-a60c-0e8a7880b408', 'SHRS-CERT-SS-2026-000085-155CE', '717188855323348', 'Thoirah Makinde', 'female', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '155ce41c4d8db51286a7dabd5af874f0d666f852d2a96a631fc5b732df20b2d5', 3)
  ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- 3. THE NUMBERING, PROTECTED.
--
--    The engraved number comes from stage_certificate_serial_seq. After this
--    import it must stand at 85, so the next certificate the Registrar
--    issues is 000086 — never a number this batch has already spent, every one of
--    which is the head of its own certificate’s content hash and cannot be
--    re-derived for a different child.
--
--    GREATEST, not a bare setval, for two reasons. It is order-independent,
--    so importing these batches in either order lands in the same place. And
--    it can only move the counter FORWARD: if production has somehow already
--    issued beyond 85, this will not wind it back on top of that work.
--    The value is read from the table, not assumed.
-- ─────────────────────────────────────────────────────────────────────────
SELECT setval('stage_certificate_serial_seq', GREATEST(
  (SELECT COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1]::int), 0) FROM stage_certificates),
  (SELECT last_value FROM stage_certificate_serial_seq)
), true);

--    stage_certificates.id has its own SERIAL sequence, and an INSERT that
--    supplies id explicitly does NOT advance it. Leaving it behind is a
--    silent fault, not a loud one: the next certificate inserts cleanly with
--    id 1, and because the archive reference and the Code 128 payload both
--    derive from cert.id while the engraved number derives from the serial
--    sequence, that certificate would print a barcode naming a different
--    record than its own number.
SELECT setval(pg_get_serial_sequence('stage_certificates', 'id'), GREATEST(
  (SELECT COALESCE(MAX(id), 0) FROM stage_certificates),
  85
), true);

--    The permanent Student ID counter, same discipline. These IDs are for
--    life; re-issuing one to a different child is unrecoverable.
SELECT setval('student_identity_seq', GREATEST(
  (SELECT last_value FROM student_identity_seq), 85
), true);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. THE CHECK THAT MAKES ON CONFLICT DO NOTHING HONEST.
--
--    DO NOTHING is exactly right for re-running an import, and exactly wrong
--    if left unchecked: it will also swallow a genuine collision — a row
--    already occupying one of these ids, or a serial typed in by hand with
--    different content — and report success. So every certificate is read
--    back and compared against what is engraved on the sheet. Serial alone
--    is not enough; the content hash, the printed name and the Student ID
--    are compared too, because a record that merely has the right number
--    while disagreeing about the child is worse than no record.
--
--    Any mismatch raises and the entire transaction rolls back.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  bad text;
  n   int;
BEGIN
  WITH issued(serial_no, content_hash, student_identity_no, student_full_name) AS (VALUES
    ('SHRS-CERT-QUR-2026-000053-1ADE9', '1ade9bd8950c1b9324591e95491407cfecad1c8d8d88316418765dd1faa85c60', '717988020633236', 'Aisha Omoshalewa Anofi'),
    ('SHRS-CERT-QUR-2026-000054-FC895', 'fc895519391ab1ba4b63cfb6081e421ea00e4ae2945f1f9f786f2e75c3922d4b', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-QUR-2026-000055-D7E3F', 'd7e3fd84b322195dc6e7d736da7e3e1f92fe868d19c2f5e108a95fec362e17fd', '716656078450081', 'Zaynab Zakariya Anofi'),
    ('SHRS-CERT-TMH-2026-000056-8DD83', '8dd83efd591de4c472c732f970ce7e697cca579a188201a3da3a0742ec124a60', '711232557821021', 'Abdulbasit Adedokun'),
    ('SHRS-CERT-IBT-2026-000057-DEE3D', 'dee3d8b43fd2a5b868bab9a5bd0e10e277d6642cf9668f3ca8d594b438828ba0', '719900615637876', 'Ameerah Abdulhafeez'),
    ('SHRS-CERT-IBT-2026-000058-05F84', '05f84deb2e4ea8d96e43a1f5ee753573fd372b343ef1f94004c5e97798de49df', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-IBT-2026-000059-0C5E5', '0c5e5e2663927fcb5ab3f03059bbda2860aad3d86e9d869e6c02540e2f1f84b1', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-IDD-2026-000060-9051A', '9051ad852be630c3cd7d0490504bc55cb594510db3cd1c9b379fdde276772706', '713145152825668', 'Yaseer Balogun'),
    ('SHRS-CERT-PRY-2026-000061-64493', '6449385db0cfa54ccfb3dae9e6c842be0770638556df6bd0a307365eab9206d2', '716389690013455', 'Aisha Lawal'),
    ('SHRS-CERT-PRY-2026-000062-0359E', '0359e5a21d8b20f2786e13d4bdfce3a4fa6999309cdd98ad58849a627a22cf5b', '719634227201249', 'Al-ameen Okoh'),
    ('SHRS-CERT-PRY-2026-000063-D9951', 'd99513ea989835bcb38a26044fe86d9c1e0e0709e3f5927139a2f72663a5c1ef', '717721632196601', 'Ashraf Korede Ojewumi'),
    ('SHRS-CERT-PRY-2026-000064-2C831', '2c831113a098a2935540ac5102a1913fbbd3eddc483f758b766dfa3b06c83213', '712878764389035', 'Daud Aliu'),
    ('SHRS-CERT-PRY-2026-000065-5E4DD', '5e4dd38dc4622c9cdacc3e7720fb53f39b5f9455e2ebaa1b9d813f55e9dc395d', '710966169384396', 'Imran Iremide Adegoke'),
    ('SHRS-CERT-PRY-2026-000066-DA467', 'da467e5fbda3c50a89d0f5987e453dc2551a259233a2b7e8999cb89758a7e0b9', '714477095008816', 'Naheemah Ismail'),
    ('SHRS-CERT-JSS-2026-000067-B0CEA', 'b0cea79f7dfa7c92358a8f3039a03db246310527cb596046df584d46ac9f4757', '716123301576828', 'Abdulrahman Abdullah'),
    ('SHRS-CERT-JSS-2026-000068-3D224', '3d224d8a8b9b6ee2e3e041dd41be59d35d6fa8c573b181c6531a619953e8387d', '717988020633236', 'Aisha Omoshalewa Anofi'),
    ('SHRS-CERT-JSS-2026-000069-D6D81', 'd6d810dff0453b217a38cebe5177845aa100aca045a73cd6092e6799f1c4acbb', '719367838764616', 'Allison Ganiyah'),
    ('SHRS-CERT-JSS-2026-000070-35EF4', '35ef45f6a4451a47a6a7490d8bc36d41f311a3aa7666112fd7e06f162e98f52e', '719900615637876', 'Ameerah Abdulhafeez'),
    ('SHRS-CERT-JSS-2026-000071-658B5', '658b52a03044f84a40a30fc51b6780f4a82d08afadcc142119b207d8b37e9f62', '712612375952406', 'Ameerah Durodola'),
    ('SHRS-CERT-JSS-2026-000072-B2F00', 'b2f00be68d82fc089a448fd7479164c2da2b36f1bf64abd70554f87d9f065a2c', '715856913140191', 'Anisa Opeyemi Jokomba'),
    ('SHRS-CERT-JSS-2026-000073-8681B', '8681bac10da5382857676e17dd306adc1bd6bf17d3a76c7bbd0afb9f56de35ba', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-JSS-2026-000074-3441D', '3441db123522675ffc16f2a7a6182eb390a11dce8e6168b49f06c948ca3bd4ce', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-JSS-2026-000075-99C19', '99c195ca321f7bb9af20559ef8ec3064138b42fe9abffda8e41571d5c968a418', '719101450327984', 'Fatimah Desire Ibrahim'),
    ('SHRS-CERT-JSS-2026-000076-C4FF9', 'c4ff9f1f46da06afac0dfa5dc6a987a456fe681cd91c4a78f1ae365181721cdc', '712345987515770', 'Fawaz Owolabi'),
    ('SHRS-CERT-JSS-2026-000077-29A2D', '29a2dc9c7c94e8ca4e709c3365ec1b56e757abfb0c11e8f458052c4d06b717d4', '714743483445443', 'Hameedah Adebimpe Ojewumi'),
    ('SHRS-CERT-JSS-2026-000078-91C8A', '91c8a522c1ff8c849349da471429716669a1e8afba212dee649b89412209dbcc', '715590524703564', 'Jubril Lawal'),
    ('SHRS-CERT-JSS-2026-000079-16768', '1676894a253c6795adc61d54c7774308ec337de30d455034fcc96873a90b7dfb', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-JSS-2026-000080-88AB8', '88ab8d41a82ac0f5f1fbbb3020d57faade29fd6b7b6206420d8dc4ae1d7e6a66', '718835061891356', 'Radiah Apatira'),
    ('SHRS-CERT-JSS-2026-000081-969B6', '969b6ba0f38960a9f05feac591792f7073808b3fcdc44ff4280b37accc0431d7', '712079599079145', 'Sa''''ad Sanusi'),
    ('SHRS-CERT-SS-2026-000082-0F4C1', '0f4c191cef9f2f5915095f93afd515e87af3a0e3259f22e39a8a93010ea66430', '710433392511139', 'Abdulbasit Amobi Jabarr'),
    ('SHRS-CERT-SS-2026-000083-4721C', '4721cf58716f6cde94c5d9eb749adcdd607ed762f321647edf99b39f583c8cd8', '715324136266939', 'Aisha Shode'),
    ('SHRS-CERT-SS-2026-000084-3CF47', '3cf4765f35cf7ce0f488aff5cd515e31c021956a69df309a9f8123afdd30b2b7', '718568673454723', 'Mazeed Hassan-Murtala'),
    ('SHRS-CERT-SS-2026-000085-155CE', '155ce41c4d8db51286a7dabd5af874f0d666f852d2a96a631fc5b732df20b2d5', '717188855323348', 'Thoirah Makinde')
  )
  SELECT string_agg(issued.serial_no || ' — ' || reason, E'\n    '), count(*)
    INTO bad, n
  FROM issued
  CROSS JOIN LATERAL (
    SELECT CASE
      WHEN c.id IS NULL THEN 'no record on file after import'
      WHEN lower(c.content_hash) IS DISTINCT FROM lower(issued.content_hash)
        THEN 'record content hash disagrees with the certificate'
      WHEN c.student_full_name IS DISTINCT FROM issued.student_full_name
        THEN 'record names ' || COALESCE(c.student_full_name, '(null)')
             || ', certificate names ' || issued.student_full_name
      WHEN c.student_identity_no IS DISTINCT FROM issued.student_identity_no
        THEN 'record Student ID disagrees with the certificate'
    END AS reason
    FROM (SELECT 1) _
    LEFT JOIN stage_certificates c ON c.serial_no = issued.serial_no
  ) chk
  WHERE chk.reason IS NOT NULL;

  IF n > 0 THEN
    RAISE EXCEPTION E'IMPORT ABORTED — % certificate(s) do not agree with the issued documents:\n    %', n, bad;
  END IF;

  IF (SELECT last_value FROM stage_certificate_serial_seq) < 85 THEN
    RAISE EXCEPTION 'IMPORT ABORTED — serial sequence stands at %, below the highest issued number 85. The next certificate would re-use a printed number.',
      (SELECT last_value FROM stage_certificate_serial_seq);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- 5. AFTER-STATE, and the one thing that legitimately needs a human.
--    Any child listed under "student record not linked" holds a valid
--    certificate that verifies correctly; their row in students is simply
--    missing or filed under a different spelling. Give the list to the
--    Registrar's Office. Do not edit this file to force a match.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'AFTER   certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'AFTER   highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'AFTER   serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   next certificate will be', (last_value + 1)::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   student id sequence stands at', last_value::text FROM student_identity_seq;

SELECT 'student record not linked' AS check, c.student_full_name AS value
FROM stage_certificates c
WHERE c.serial_no IN ('SHRS-CERT-QUR-2026-000053-1ADE9', 'SHRS-CERT-QUR-2026-000054-FC895', 'SHRS-CERT-QUR-2026-000055-D7E3F', 'SHRS-CERT-TMH-2026-000056-8DD83', 'SHRS-CERT-IBT-2026-000057-DEE3D', 'SHRS-CERT-IBT-2026-000058-05F84', 'SHRS-CERT-IBT-2026-000059-0C5E5', 'SHRS-CERT-IDD-2026-000060-9051A', 'SHRS-CERT-PRY-2026-000061-64493', 'SHRS-CERT-PRY-2026-000062-0359E', 'SHRS-CERT-PRY-2026-000063-D9951', 'SHRS-CERT-PRY-2026-000064-2C831', 'SHRS-CERT-PRY-2026-000065-5E4DD', 'SHRS-CERT-PRY-2026-000066-DA467', 'SHRS-CERT-JSS-2026-000067-B0CEA', 'SHRS-CERT-JSS-2026-000068-3D224', 'SHRS-CERT-JSS-2026-000069-D6D81', 'SHRS-CERT-JSS-2026-000070-35EF4', 'SHRS-CERT-JSS-2026-000071-658B5', 'SHRS-CERT-JSS-2026-000072-B2F00', 'SHRS-CERT-JSS-2026-000073-8681B', 'SHRS-CERT-JSS-2026-000074-3441D', 'SHRS-CERT-JSS-2026-000075-99C19', 'SHRS-CERT-JSS-2026-000076-C4FF9', 'SHRS-CERT-JSS-2026-000077-29A2D', 'SHRS-CERT-JSS-2026-000078-91C8A', 'SHRS-CERT-JSS-2026-000079-16768', 'SHRS-CERT-JSS-2026-000080-88AB8', 'SHRS-CERT-JSS-2026-000081-969B6', 'SHRS-CERT-SS-2026-000082-0F4C1', 'SHRS-CERT-SS-2026-000083-4721C', 'SHRS-CERT-SS-2026-000084-3CF47', 'SHRS-CERT-SS-2026-000085-155CE')
  AND NOT EXISTS (
    SELECT 1 FROM students s WHERE s.identity_no = c.student_identity_no
  )
ORDER BY 2;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- NOT FINISHED HERE. A successful import is not a working verification page.
-- Prove it against the real public endpoint before telling anyone it is
-- fixed, and before any further sheet is released:
--
--     node scripts/verify-issued-certificates-live.mjs --full
-- ─────────────────────────────────────────────────────────────────────────
