-- SHRS GRADUATION REGISTER — PRODUCTION IMPORT
-- Generated by scripts/build-production-import.mjs from the sealed registers:
--     docs/graduation-registers/2026-08-08-QUR-000051.sql
--     docs/graduation-registers/2026-08-08-TMH-000054.sql
--     docs/graduation-registers/2026-08-08-IBT-000055.sql
--     docs/graduation-registers/2026-08-08-IDD-000058.sql
--     docs/graduation-registers/2026-08-08-PRY-000059.sql
--     docs/graduation-registers/2026-08-08-JSS-000065.sql
--     docs/graduation-registers/2026-08-08-SS-000080.sql
--
-- 33 certificates, minted on 15 August 2026 under key version 3 for the
-- graduands of the 8 August ceremony who had no certificate record at all.
-- Their numbers, names, Student IDs and content hashes are fixed the moment
-- they are minted, because the five characters engraved on the face are the
-- head of the content hash. This file creates their RECORDS. It changes nothing about
-- the documents and cannot: every INSERT below is a verbatim copy of the
-- sealed register's own statement, and the generator asserts that copy is
-- exact before writing. No identifier and no cryptographic field is
-- recomputed anywhere in this file.
--
-- SAFE TO RUN TWICE. Every insert carries ON CONFLICT DO NOTHING and the
-- sequence repairs can only move a counter forward, so a second execution
-- leaves the database byte-for-byte unchanged.
--
-- ONE TRANSACTION. If any check at the end fails, the whole import rolls
-- back and the database is exactly as it was. A half-imported cohort is the
-- one state harder to recover from than no import at all.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────
-- 0. BEFORE-STATE. Read, never assume. These rows are informational and are
--    printed by psql as the transaction runs, so the operator can see what
--    production actually held before anything was written.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'BEFORE  certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'BEFORE  highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'BEFORE  serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'BEFORE  student id sequence stands at', last_value::text FROM student_identity_seq;

-- ─────────────────────────────────────────────────────────────────────────
-- 1. PERMANENT STUDENT IDs, attached to the children who already hold them.
--    Guarded by identity_no IS NULL: a student who already carries an ID is
--    never overwritten, which makes these idempotent AND makes them refuse
--    to silently change a number that is printed on a document. A student
--    row that does not exist matches nothing and reports UPDATE 0 — the
--    certificate still verifies, because the certificate row carries the ID
--    itself; the child's record is simply not yet linked, and §5 lists it.
-- ─────────────────────────────────────────────────────────────────────────
UPDATE students SET identity_no = '711232557821021' WHERE full_name = 'Abdulbasit Adedokun' AND identity_no IS NULL;
UPDATE students SET identity_no = '716656078450081' WHERE full_name = 'Ameerah Abdulhafeez' AND identity_no IS NULL;
UPDATE students SET identity_no = '713944318135552' WHERE full_name = 'Faridah Ayomide Aliu' AND identity_no IS NULL;
UPDATE students SET identity_no = '717455243759974' WHERE full_name = 'Muhammad Ismail Seriki' AND identity_no IS NULL;
UPDATE students SET identity_no = '719900615637876' WHERE full_name = 'Yaseer Balogun' AND identity_no IS NULL;

-- ─────────────────────────────────────────────────────────────────────────
-- 2. THE CERTIFICATES. Verbatim from the sealed registers. The only edit is
--    the conflict clause.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (51, '813e02e7-d90b-5bcc-bf81-642e71088309', 'SHRS-CERT-QUR-2026-000051-890BF', '717988020633236', 'Aisha Omoshalewa Anofi', 'female', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '890bf4bca1618975c05a14be26df5da073f84a18a1ecd0187bad4b0c0c8d8033', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (52, '4d3a35db-442d-5d42-bb10-cd77b23429ab', 'SHRS-CERT-QUR-2026-000052-0BFD3', '710699780947768', 'Baqi Olamiposi Anofi', 'male', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '0bfd30841933c6c585e83962990dd1c68060eb1892108c9482a3ea969e6ef933', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (53, 'c86a85f8-2723-5ff5-aae5-fbe141653b38', 'SHRS-CERT-QUR-2026-000053-7556C', '713411541262298', 'Zaynab Zakariya Anofi', 'female', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '7556c80b8d963ae55af71445756bfdb0165edc7f04fcf37a0a2f6f6fae4e5c6e', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (54, '795124d7-7eb2-5745-8776-053fd4b23008', 'SHRS-CERT-TMH-2026-000054-7CC6F', '711232557821021', 'Abdulbasit Adedokun', 'عبد الباسط أددوكن', 'male', 'TMH', 'Tamhīdiyyah — Preparatory Stage', 'المرحلة التمهيدية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '7cc6fe3de08868d008d3357ca8ae95c59f3d1639e0ef002c08369ce6bb4ffd6f', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (55, '40e6c648-7b63-5c43-8b61-2bb91083c01e', 'SHRS-CERT-IBT-2026-000055-1F758', '716656078450081', 'Ameerah Abdulhafeez', 'أميرة عبد الحفيظ', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '1f75871a518addca3b1ddd4c3aa7b75b74ad74e1a0b15f97cf2953313005736b', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (56, '559ab3d1-21ab-5695-b02f-b89242f874c3', 'SHRS-CERT-IBT-2026-000056-C1244', '713944318135552', 'Faridah Ayomide Aliu', 'فريدة أيومدي علي', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'c1244ebafe3792355c4ee1abfe801d60710c6075dc7a4268c34ef770b3b4c3f7', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (57, '37a0d8a5-cff6-55e0-a324-f526f169affb', 'SHRS-CERT-IBT-2026-000057-91D78', '717455243759974', 'Muhammad Ismail Seriki', 'محمد إسماعيل سركي', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '91d78e9b1dd6d3343a5371dfbdf952143e7d06385874549a355e5f91a5d0732b', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (58, 'f9241001-f497-53c9-9281-3c780ef2e5ae', 'SHRS-CERT-IDD-2026-000058-C6381', '719900615637876', 'Yaseer Balogun', 'ياسر بالوغون', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'c6381bd4930bbf49c5c5c3b78715a21b4d74cb721cb963cf2a684ded2f453df5', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (59, '9445d630-6454-58dc-a71a-60b8a8701dd3', 'SHRS-CERT-PRY-2026-000059-C7997', '713145152825668', 'Aisha Lawal', 'female', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'c7997e5e05b4fb9e87890fef88699e92f3d4e38debb649972fa1e02a0b88e59d', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (60, '99c1c327-8452-596b-88d2-15e806727c82', 'SHRS-CERT-PRY-2026-000060-F3021', '716389690013455', 'Al-ameen Okoh', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'f3021611f9274129ccd69971367a2fd4cce2a4d703553a64b252896080a91e02', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (61, 'f252e986-0b78-5d14-9f0d-2a15893a49a2', 'SHRS-CERT-PRY-2026-000061-33E36', '717721632196601', 'Ashraf Korede Ojewumi', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '33e361cbe89cab700cbcdc0567dcb3e07b3c0f728dcab8ed9c051911357d1c8e', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (62, '79c7eda4-467c-5875-9870-166388875e5a', 'SHRS-CERT-PRY-2026-000062-91BD3', '719634227201249', 'Daud Aliu', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '91bd308a0cc4ec65ffb4d43998e4fbbc41d523cef648eff3578ad25f7eeb1bc8', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (63, '0bd1e0b8-f9c1-552c-ad54-d0aaf28d226f', 'SHRS-CERT-PRY-2026-000063-E9A53', '710966169384396', 'Imran Iremide Adegoke', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'e9a5393b78f2d1e314635fbcab203b5e21a54beece25b0a712cf9d84e5ce51db', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (64, '57dad779-855d-5a47-9b28-f72c0047b74d', 'SHRS-CERT-PRY-2026-000064-B2C46', '714477095008816', 'Naheemah Ismail', 'female', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'b2c46396e14b8b167ee6eae9f673f9ce0d8533712cb00a8513b46a2a7fb9c37a', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (65, '95986098-483f-50a2-aee1-63129a88e93c', 'SHRS-CERT-JSS-2026-000065-48606', '712878764389035', 'Abdulrahman Abdullah', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '48606926c01847a8b065c6b759b5317e0383ac443580bdbc328c2009ed75a944', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (66, '32cfea0b-5837-50bc-8de0-cbb6ff20db43', 'SHRS-CERT-JSS-2026-000066-C52E5', '717988020633236', 'Aisha Omoshalewa Anofi', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'c52e5c7da306850f91e3e8bbe82c7322705e472896931361b8cf1a71538437f3', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (67, '60a0bf86-df08-58e1-832a-422a8be3f229', 'SHRS-CERT-JSS-2026-000067-9C9B2', '716123301576828', 'Allison Ganiyah', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '9c9b22612065c2286bef07d7e6bd85f8ee33cb1579b78632dd7b32f107fee9aa', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (68, '29c5cd9e-6b1d-52a2-bf4c-2d4e5b22af69', 'SHRS-CERT-JSS-2026-000068-65F5F', '716656078450081', 'Ameerah Abdulhafeez', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '65f5f6cc4464396af71a50e0bc943b32e228c56091e9a54e200d9785240d2c9a', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (69, '1a2496f6-e8ef-5b15-8380-b617f3845fd9', 'SHRS-CERT-JSS-2026-000069-77D29', '719367838764616', 'Ameerah Durodola', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '77d290c1211a195a418c90587d10117bdba72088e2a74d99364785e8a67cbe64', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (70, '6ec1c72c-7c2a-569e-a69b-f0de4dd7339d', 'SHRS-CERT-JSS-2026-000070-2D5A6', '712612375952406', 'Anisa Opeyemi Jokomba', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '2d5a6b92723a1d0406bb58396f152ea8b660590696b63d5b1b3b74eac1c0a674', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (71, '0f74cf88-15fe-51c1-aa69-ccd097fd55d2', 'SHRS-CERT-JSS-2026-000071-14CDF', '710699780947768', 'Baqi Olamiposi Anofi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '14cdfacbe83cbb0458d01144e763c28ced34396f051ccd3bb9f067ddc47c35df', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (72, '2b2a298a-6239-5ecf-9ee0-375abc74760a', 'SHRS-CERT-JSS-2026-000072-8EF9D', '713944318135552', 'Faridah Ayomide Aliu', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '8ef9dedb5e4fd5fb161584f409ea6bb274f6c57487d059b9c0a77eb01461e24e', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (73, '9f744b41-ce25-5a46-873c-8421b7a44a99', 'SHRS-CERT-JSS-2026-000073-2C155', '715856913140191', 'Fatimah Desire Ibrahim', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '2c155db448c689e3ff0520d0719fe8af59dfc9c6ff4a44e8a73f91c90411a213', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (74, '084be30f-45e6-5eb5-a31f-496d353c650b', 'SHRS-CERT-JSS-2026-000074-23BC0', '719101450327984', 'Fawaz Owolabi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '23bc00953d454bf67d49dcda7949f445f7d2e3ce634f0b3c14cc706641b9f8a8', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (75, '69470a21-05d9-59a0-b2d0-cd018e593d47', 'SHRS-CERT-JSS-2026-000075-0F568', '714743483445443', 'Hameedah Adebimpe Ojewumi', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '0f56844ef8020b48b2d546555d1d0e5cc0f40db5d6f45141c761e476dca3e903', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (76, 'c2d5a744-da8a-576b-a06e-16d88282fd0d', 'SHRS-CERT-JSS-2026-000076-B151F', '712345987515770', 'Jubril Lawal', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'b151fa2ba4296a56bee7895baf1755d1ae48cdcf0571c7abff7ffc6703c749bd', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (77, '02c15237-9429-580c-9e9c-6cd78187be4c', 'SHRS-CERT-JSS-2026-000077-FBCD3', '717455243759974', 'Muhammad Ismail Seriki', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'fbcd32311204849ccd7d11407c7363c4c903709515efdef2c0f9fe6887208d4b', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (78, '589ad2a1-deb4-5a4f-a82f-06fbc4949b55', 'SHRS-CERT-JSS-2026-000078-2EE5D', '715590524703564', 'Radiah Apatira', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '2ee5d7f68e732000d9b710c68d4790f441c4fbe127d394958e1a9f7a6287e8ea', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (79, '5a710d09-56f1-52fb-8f8f-ea877aa7fc37', 'SHRS-CERT-JSS-2026-000079-163F2', '718835061891356', 'Sa''ad Sanusi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '163f2142af99c53a18010fc5bcdac772629c53ffdec43cc113bed75fad90fb00', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (80, '3b1184c1-36b7-57e7-b0f7-c88f55077d76', 'SHRS-CERT-SS-2026-000080-29DD5', '710433392511139', 'Abdulbasit Amobi Jabarr', 'male', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '29dd5055d87996f6c89851974af80f1fb59adf21b7885c17ba895d0e966b787e', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (81, '6bc8e0aa-ddf6-5f66-91c4-410537c85867', 'SHRS-CERT-SS-2026-000081-A3178', '712079599079145', 'Aisha Shode', 'female', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'a3178c9086d17833b35776f4bf663c8f9210285064d0440c4684ad21f4350fab', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (82, '3e3610a8-bb73-5904-87e6-a613cd919b41', 'SHRS-CERT-SS-2026-000082-5CC78', '715324136266939', 'Mazeed Hassan-Murtala', 'male', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '5cc78fb22f78ebdb7eceee76952be6aeec1ae4ce7297fff710dfb57fa09790df', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, credential_id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (83, '2343c9f0-744d-5c0d-ac58-c6e1d0a6cebf', 'SHRS-CERT-SS-2026-000083-AA6F4', '717188855323348', 'Thoirah Makinde', 'female', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'aa6f4a0ca1288a05820db2cb7e33eac671b863cbaf1a3e0a4911c6398cb6ee3e', 3)
  ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- 3. THE NUMBERING, PROTECTED.
--
--    The engraved number comes from stage_certificate_serial_seq. After this
--    import it must stand at 83, so the next certificate the Registrar
--    issues is 000084 — never a number this batch has already spent, every one of
--    which is the head of its own certificate’s content hash and cannot be
--    re-derived for a different child.
--
--    GREATEST, not a bare setval, for two reasons. It is order-independent,
--    so importing these batches in either order lands in the same place. And
--    it can only move the counter FORWARD: if production has somehow already
--    issued beyond 83, this will not wind it back on top of that work.
--    The value is read from the table, not assumed.
-- ─────────────────────────────────────────────────────────────────────────
SELECT setval('stage_certificate_serial_seq', GREATEST(
  (SELECT COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1]::int), 0) FROM stage_certificates),
  (SELECT last_value FROM stage_certificate_serial_seq)
), true);

--    stage_certificates.id has its own SERIAL sequence, and an INSERT that
--    supplies id explicitly does NOT advance it. Leaving it behind is a
--    silent fault, not a loud one: the next certificate inserts cleanly with
--    id 1, and because the archive reference and the Code 128 payload both
--    derive from cert.id while the engraved number derives from the serial
--    sequence, that certificate would print a barcode naming a different
--    record than its own number.
SELECT setval(pg_get_serial_sequence('stage_certificates', 'id'), GREATEST(
  (SELECT COALESCE(MAX(id), 0) FROM stage_certificates),
  83
), true);

--    The permanent Student ID counter, same discipline. These IDs are for
--    life; re-issuing one to a different child is unrecoverable.
SELECT setval('student_identity_seq', GREATEST(
  (SELECT last_value FROM student_identity_seq), 83
), true);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. THE CHECK THAT MAKES ON CONFLICT DO NOTHING HONEST.
--
--    DO NOTHING is exactly right for re-running an import, and exactly wrong
--    if left unchecked: it will also swallow a genuine collision — a row
--    already occupying one of these ids, or a serial typed in by hand with
--    different content — and report success. So every certificate is read
--    back and compared against what is engraved on the sheet. Serial alone
--    is not enough; the content hash, the printed name and the Student ID
--    are compared too, because a record that merely has the right number
--    while disagreeing about the child is worse than no record.
--
--    Any mismatch raises and the entire transaction rolls back.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  bad text;
  n   int;
BEGIN
  WITH issued(serial_no, content_hash, student_identity_no, student_full_name) AS (VALUES
    ('SHRS-CERT-QUR-2026-000051-890BF', '890bf4bca1618975c05a14be26df5da073f84a18a1ecd0187bad4b0c0c8d8033', '717988020633236', 'Aisha Omoshalewa Anofi'),
    ('SHRS-CERT-QUR-2026-000052-0BFD3', '0bfd30841933c6c585e83962990dd1c68060eb1892108c9482a3ea969e6ef933', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-QUR-2026-000053-7556C', '7556c80b8d963ae55af71445756bfdb0165edc7f04fcf37a0a2f6f6fae4e5c6e', '713411541262298', 'Zaynab Zakariya Anofi'),
    ('SHRS-CERT-TMH-2026-000054-7CC6F', '7cc6fe3de08868d008d3357ca8ae95c59f3d1639e0ef002c08369ce6bb4ffd6f', '711232557821021', 'Abdulbasit Adedokun'),
    ('SHRS-CERT-IBT-2026-000055-1F758', '1f75871a518addca3b1ddd4c3aa7b75b74ad74e1a0b15f97cf2953313005736b', '716656078450081', 'Ameerah Abdulhafeez'),
    ('SHRS-CERT-IBT-2026-000056-C1244', 'c1244ebafe3792355c4ee1abfe801d60710c6075dc7a4268c34ef770b3b4c3f7', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-IBT-2026-000057-91D78', '91d78e9b1dd6d3343a5371dfbdf952143e7d06385874549a355e5f91a5d0732b', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-IDD-2026-000058-C6381', 'c6381bd4930bbf49c5c5c3b78715a21b4d74cb721cb963cf2a684ded2f453df5', '719900615637876', 'Yaseer Balogun'),
    ('SHRS-CERT-PRY-2026-000059-C7997', 'c7997e5e05b4fb9e87890fef88699e92f3d4e38debb649972fa1e02a0b88e59d', '713145152825668', 'Aisha Lawal'),
    ('SHRS-CERT-PRY-2026-000060-F3021', 'f3021611f9274129ccd69971367a2fd4cce2a4d703553a64b252896080a91e02', '716389690013455', 'Al-ameen Okoh'),
    ('SHRS-CERT-PRY-2026-000061-33E36', '33e361cbe89cab700cbcdc0567dcb3e07b3c0f728dcab8ed9c051911357d1c8e', '717721632196601', 'Ashraf Korede Ojewumi'),
    ('SHRS-CERT-PRY-2026-000062-91BD3', '91bd308a0cc4ec65ffb4d43998e4fbbc41d523cef648eff3578ad25f7eeb1bc8', '719634227201249', 'Daud Aliu'),
    ('SHRS-CERT-PRY-2026-000063-E9A53', 'e9a5393b78f2d1e314635fbcab203b5e21a54beece25b0a712cf9d84e5ce51db', '710966169384396', 'Imran Iremide Adegoke'),
    ('SHRS-CERT-PRY-2026-000064-B2C46', 'b2c46396e14b8b167ee6eae9f673f9ce0d8533712cb00a8513b46a2a7fb9c37a', '714477095008816', 'Naheemah Ismail'),
    ('SHRS-CERT-JSS-2026-000065-48606', '48606926c01847a8b065c6b759b5317e0383ac443580bdbc328c2009ed75a944', '712878764389035', 'Abdulrahman Abdullah'),
    ('SHRS-CERT-JSS-2026-000066-C52E5', 'c52e5c7da306850f91e3e8bbe82c7322705e472896931361b8cf1a71538437f3', '717988020633236', 'Aisha Omoshalewa Anofi'),
    ('SHRS-CERT-JSS-2026-000067-9C9B2', '9c9b22612065c2286bef07d7e6bd85f8ee33cb1579b78632dd7b32f107fee9aa', '716123301576828', 'Allison Ganiyah'),
    ('SHRS-CERT-JSS-2026-000068-65F5F', '65f5f6cc4464396af71a50e0bc943b32e228c56091e9a54e200d9785240d2c9a', '716656078450081', 'Ameerah Abdulhafeez'),
    ('SHRS-CERT-JSS-2026-000069-77D29', '77d290c1211a195a418c90587d10117bdba72088e2a74d99364785e8a67cbe64', '719367838764616', 'Ameerah Durodola'),
    ('SHRS-CERT-JSS-2026-000070-2D5A6', '2d5a6b92723a1d0406bb58396f152ea8b660590696b63d5b1b3b74eac1c0a674', '712612375952406', 'Anisa Opeyemi Jokomba'),
    ('SHRS-CERT-JSS-2026-000071-14CDF', '14cdfacbe83cbb0458d01144e763c28ced34396f051ccd3bb9f067ddc47c35df', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-JSS-2026-000072-8EF9D', '8ef9dedb5e4fd5fb161584f409ea6bb274f6c57487d059b9c0a77eb01461e24e', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-JSS-2026-000073-2C155', '2c155db448c689e3ff0520d0719fe8af59dfc9c6ff4a44e8a73f91c90411a213', '715856913140191', 'Fatimah Desire Ibrahim'),
    ('SHRS-CERT-JSS-2026-000074-23BC0', '23bc00953d454bf67d49dcda7949f445f7d2e3ce634f0b3c14cc706641b9f8a8', '719101450327984', 'Fawaz Owolabi'),
    ('SHRS-CERT-JSS-2026-000075-0F568', '0f56844ef8020b48b2d546555d1d0e5cc0f40db5d6f45141c761e476dca3e903', '714743483445443', 'Hameedah Adebimpe Ojewumi'),
    ('SHRS-CERT-JSS-2026-000076-B151F', 'b151fa2ba4296a56bee7895baf1755d1ae48cdcf0571c7abff7ffc6703c749bd', '712345987515770', 'Jubril Lawal'),
    ('SHRS-CERT-JSS-2026-000077-FBCD3', 'fbcd32311204849ccd7d11407c7363c4c903709515efdef2c0f9fe6887208d4b', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-JSS-2026-000078-2EE5D', '2ee5d7f68e732000d9b710c68d4790f441c4fbe127d394958e1a9f7a6287e8ea', '715590524703564', 'Radiah Apatira'),
    ('SHRS-CERT-JSS-2026-000079-163F2', '163f2142af99c53a18010fc5bcdac772629c53ffdec43cc113bed75fad90fb00', '718835061891356', 'Sa''''ad Sanusi'),
    ('SHRS-CERT-SS-2026-000080-29DD5', '29dd5055d87996f6c89851974af80f1fb59adf21b7885c17ba895d0e966b787e', '710433392511139', 'Abdulbasit Amobi Jabarr'),
    ('SHRS-CERT-SS-2026-000081-A3178', 'a3178c9086d17833b35776f4bf663c8f9210285064d0440c4684ad21f4350fab', '712079599079145', 'Aisha Shode'),
    ('SHRS-CERT-SS-2026-000082-5CC78', '5cc78fb22f78ebdb7eceee76952be6aeec1ae4ce7297fff710dfb57fa09790df', '715324136266939', 'Mazeed Hassan-Murtala'),
    ('SHRS-CERT-SS-2026-000083-AA6F4', 'aa6f4a0ca1288a05820db2cb7e33eac671b863cbaf1a3e0a4911c6398cb6ee3e', '717188855323348', 'Thoirah Makinde')
  )
  SELECT string_agg(issued.serial_no || ' — ' || reason, E'\n    '), count(*)
    INTO bad, n
  FROM issued
  CROSS JOIN LATERAL (
    SELECT CASE
      WHEN c.id IS NULL THEN 'no record on file after import'
      WHEN lower(c.content_hash) IS DISTINCT FROM lower(issued.content_hash)
        THEN 'record content hash disagrees with the certificate'
      WHEN c.student_full_name IS DISTINCT FROM issued.student_full_name
        THEN 'record names ' || COALESCE(c.student_full_name, '(null)')
             || ', certificate names ' || issued.student_full_name
      WHEN c.student_identity_no IS DISTINCT FROM issued.student_identity_no
        THEN 'record Student ID disagrees with the certificate'
    END AS reason
    FROM (SELECT 1) _
    LEFT JOIN stage_certificates c ON c.serial_no = issued.serial_no
  ) chk
  WHERE chk.reason IS NOT NULL;

  IF n > 0 THEN
    RAISE EXCEPTION E'IMPORT ABORTED — % certificate(s) do not agree with the issued documents:\n    %', n, bad;
  END IF;

  IF (SELECT last_value FROM stage_certificate_serial_seq) < 83 THEN
    RAISE EXCEPTION 'IMPORT ABORTED — serial sequence stands at %, below the highest issued number 83. The next certificate would re-use a printed number.',
      (SELECT last_value FROM stage_certificate_serial_seq);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- 5. AFTER-STATE, and the one thing that legitimately needs a human.
--    Any child listed under "student record not linked" holds a valid
--    certificate that verifies correctly; their row in students is simply
--    missing or filed under a different spelling. Give the list to the
--    Registrar's Office. Do not edit this file to force a match.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'AFTER   certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'AFTER   highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'AFTER   serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   next certificate will be', (last_value + 1)::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   student id sequence stands at', last_value::text FROM student_identity_seq;

SELECT 'student record not linked' AS check, c.student_full_name AS value
FROM stage_certificates c
WHERE c.serial_no IN ('SHRS-CERT-QUR-2026-000051-890BF', 'SHRS-CERT-QUR-2026-000052-0BFD3', 'SHRS-CERT-QUR-2026-000053-7556C', 'SHRS-CERT-TMH-2026-000054-7CC6F', 'SHRS-CERT-IBT-2026-000055-1F758', 'SHRS-CERT-IBT-2026-000056-C1244', 'SHRS-CERT-IBT-2026-000057-91D78', 'SHRS-CERT-IDD-2026-000058-C6381', 'SHRS-CERT-PRY-2026-000059-C7997', 'SHRS-CERT-PRY-2026-000060-F3021', 'SHRS-CERT-PRY-2026-000061-33E36', 'SHRS-CERT-PRY-2026-000062-91BD3', 'SHRS-CERT-PRY-2026-000063-E9A53', 'SHRS-CERT-PRY-2026-000064-B2C46', 'SHRS-CERT-JSS-2026-000065-48606', 'SHRS-CERT-JSS-2026-000066-C52E5', 'SHRS-CERT-JSS-2026-000067-9C9B2', 'SHRS-CERT-JSS-2026-000068-65F5F', 'SHRS-CERT-JSS-2026-000069-77D29', 'SHRS-CERT-JSS-2026-000070-2D5A6', 'SHRS-CERT-JSS-2026-000071-14CDF', 'SHRS-CERT-JSS-2026-000072-8EF9D', 'SHRS-CERT-JSS-2026-000073-2C155', 'SHRS-CERT-JSS-2026-000074-23BC0', 'SHRS-CERT-JSS-2026-000075-0F568', 'SHRS-CERT-JSS-2026-000076-B151F', 'SHRS-CERT-JSS-2026-000077-FBCD3', 'SHRS-CERT-JSS-2026-000078-2EE5D', 'SHRS-CERT-JSS-2026-000079-163F2', 'SHRS-CERT-SS-2026-000080-29DD5', 'SHRS-CERT-SS-2026-000081-A3178', 'SHRS-CERT-SS-2026-000082-5CC78', 'SHRS-CERT-SS-2026-000083-AA6F4')
  AND NOT EXISTS (
    SELECT 1 FROM students s WHERE s.identity_no = c.student_identity_no
  )
ORDER BY 2;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- NOT FINISHED HERE. A successful import is not a working verification page.
-- Prove it against the real public endpoint before telling anyone it is
-- fixed, and before any further sheet is released:
--
--     node scripts/verify-issued-certificates-live.mjs --full
-- ─────────────────────────────────────────────────────────────────────────
