-- SHRS GRADUATION REGISTER — PRODUCTION IMPORT
-- Generated by scripts/build-production-import.mjs from the sealed registers:
--     docs/graduation-registers/2026-08-08-QUR-000048.sql
--     docs/graduation-registers/2026-08-08-TMH-000051.sql
--     docs/graduation-registers/2026-08-08-IBT-000052.sql
--     docs/graduation-registers/2026-08-08-IDD-000055.sql
--     docs/graduation-registers/2026-08-08-PRY-000056.sql
--     docs/graduation-registers/2026-08-08-JSS-000062.sql
--     docs/graduation-registers/2026-08-08-SS-000077.sql
--
-- 33 certificates, minted on 15 August 2026 under key version 3 for the
-- graduands of the 8 August ceremony who had no certificate record at all.
-- Their numbers, names, Student IDs and content hashes are fixed the moment
-- they are minted, because the five characters engraved on the face are the
-- head of the content hash. This file creates their RECORDS. It changes nothing about
-- the documents and cannot: every INSERT below is a verbatim copy of the
-- sealed register's own statement, and the generator asserts that copy is
-- exact before writing. No identifier and no cryptographic field is
-- recomputed anywhere in this file.
--
-- SAFE TO RUN TWICE. Every insert carries ON CONFLICT DO NOTHING and the
-- sequence repairs can only move a counter forward, so a second execution
-- leaves the database byte-for-byte unchanged.
--
-- ONE TRANSACTION. If any check at the end fails, the whole import rolls
-- back and the database is exactly as it was. A half-imported cohort is the
-- one state harder to recover from than no import at all.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────
-- 0. BEFORE-STATE. Read, never assume. These rows are informational and are
--    printed by psql as the transaction runs, so the operator can see what
--    production actually held before anything was written.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'BEFORE  certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'BEFORE  highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'BEFORE  serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'BEFORE  student id sequence stands at', last_value::text FROM student_identity_seq;

-- ─────────────────────────────────────────────────────────────────────────
-- 1. PERMANENT STUDENT IDs, attached to the children who already hold them.
--    Guarded by identity_no IS NULL: a student who already carries an ID is
--    never overwritten, which makes these idempotent AND makes them refuse
--    to silently change a number that is printed on a document. A student
--    row that does not exist matches nothing and reports UPDATE 0 — the
--    certificate still verifies, because the certificate row carries the ID
--    itself; the child's record is simply not yet linked, and §5 lists it.
-- ─────────────────────────────────────────────────────────────────────────
UPDATE students SET identity_no = '711232557821021' WHERE full_name = 'Abdulbasit Adedokun' AND identity_no IS NULL;
UPDATE students SET identity_no = '710167004074504' WHERE full_name = 'Ameerah Abdulhafeez' AND identity_no IS NULL;
UPDATE students SET identity_no = '713944318135552' WHERE full_name = 'Faridah Ayomide Aliu' AND identity_no IS NULL;
UPDATE students SET identity_no = '717455243759974' WHERE full_name = 'Muhammad Ismail Seriki' AND identity_no IS NULL;
UPDATE students SET identity_no = '713411541262298' WHERE full_name = 'Yaseer Balogun' AND identity_no IS NULL;

-- ─────────────────────────────────────────────────────────────────────────
-- 2. THE CERTIFICATES. Verbatim from the sealed registers. The only edit is
--    the conflict clause.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (48, 'SHRS-CERT-QUR-2026-000048-64881', '717988020633236', 'Aisha Omoshalewa Anofi', 'female', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '6488133848a46191f61d2043c191a8609eb7b635a1ea9b39899ffcb2e86728b3', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (49, 'SHRS-CERT-QUR-2026-000049-1E924', '710699780947768', 'Baqi Olamiposi Anofi', 'male', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '1e9243d7cbc60da3bccf82eeef1794999a44cb004afc27e639f05843670553b3', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (50, 'SHRS-CERT-QUR-2026-000050-1FBB5', '716922466886710', 'Zaynab Zakariya Anofi', 'female', 'QUR', 'Hifz of the Glorious Qur’an', 'Sultan Hanafi Royal Schools — Sultan Hanafi Qur’an College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '1fbb5cf55454a4c002ef3b5993bb8067b200393b9b11f8f96789e02f4a5f3796', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (51, 'SHRS-CERT-TMH-2026-000051-B6558', '711232557821021', 'Abdulbasit Adedokun', 'عبد الباسط أددوكن', 'male', 'TMH', 'Tamhīdiyyah — Preparatory Stage', 'المرحلة التمهيدية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'b65588663012ffb1b5760db18c4e5307a6ea14ebfe708bb70fa2c7b02b3876c2', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (52, 'SHRS-CERT-IBT-2026-000052-21455', '710167004074504', 'Ameerah Abdulhafeez', 'أميرة عبد الحفيظ', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '21455e1fdb6c5bc0b49f62663658b5e76d5381813ea06b45a572ae4a842ad8d0', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (53, 'SHRS-CERT-IBT-2026-000053-DAEF7', '713944318135552', 'Faridah Ayomide Aliu', 'فريدة أيومدي علي', 'female', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', 'daef7da163af4312b508bb03d5ae03b49fabc9c289a36a84a44784a3813f8d44', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (54, 'SHRS-CERT-IBT-2026-000054-72EF6', '717455243759974', 'Muhammad Ismail Seriki', 'محمد إسماعيل سركي', 'male', 'IBT', 'Ibtida’iyyah — Primary Stage', 'المرحلة الابتدائية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '72ef65b35ed95b4182096658a9659e8567fc9147f41ca96a8fdbea3151364269', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_full_name_ar, student_sex, programme_code, programme_label_en, programme_label_ar, institution_name, academic_year, grade_en, grade_ar, place_en, place_ar, issued_at, issued_at_hijri, issued_at_hijri_ar, content_hash, hash_key_version) VALUES (55, 'SHRS-CERT-IDD-2026-000055-0CF24', '713411541262298', 'Yaseer Balogun', 'ياسر بالوغون', 'male', 'IDD', 'I’dādiyyah — Intermediate Stage', 'المرحلة الإعدادية', 'Sultan Hanafi Royal Schools — School of Islamic & Arabic Studies', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', 'إكورودو، لاغوس، نيجيريا', '2026-08-08', '25 Ṣafar 1448 A.H.', '25 صفر 1448هـ', '0cf24ba76de01290f3cf4ff85cf261bfaf04310f662bd1055484450c9e0741e7', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (56, 'SHRS-CERT-PRY-2026-000056-52FC6', '716656078450081', 'Aisha Lawal', 'female', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '52fc69b02e0bc1d7933fdcd956abde268db88e2b2975354879a72c4944e2a9bd', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (57, 'SHRS-CERT-PRY-2026-000057-341A7', '719900615637876', 'Al-ameen Okoh', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '341a7d43a6d7b7bdcabfa7549ebd66a593fccf2b9487ab91a9d1bfc82161c872', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (58, 'SHRS-CERT-PRY-2026-000058-FE5E3', '717721632196601', 'Ashraf Korede Ojewumi', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'fe5e3baf94e2247798e2cbdd5c8e1290d55a360f38fca50c645c211253b4995e', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (59, 'SHRS-CERT-PRY-2026-000059-D277B', '713145152825668', 'Daud Aliu', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'd277b016be9d57f44431ee73bac897130bb4cbb408d61b602dfd8ca64558bbec', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (60, 'SHRS-CERT-PRY-2026-000060-B52D7', '710966169384396', 'Imran Iremide Adegoke', 'male', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'b52d79434105d455b32bcef7a5ac402e8c41b57cd5b0a0868d7c2a69c5cf83ff', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (61, 'SHRS-CERT-PRY-2026-000061-00887', '714477095008816', 'Naheemah Ismail', 'female', 'PRY', 'Primary School', 'Sultan Hanafi Royal Schools — Sultan Hanafi Nursery and Primary School', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '0088747adb95ce21510243f721dc087eacdc844d1de5ebe7ecca58699a39e8b3', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (62, 'SHRS-CERT-JSS-2026-000062-1EA9D', '716389690013455', 'Abdulrahman Abdullah', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '1ea9dd059f0a4810a362acf262384cc49219dbc83382f7317f90276643814d84', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (63, 'SHRS-CERT-JSS-2026-000063-3D4DB', '717988020633236', 'Aisha Omoshalewa Anofi', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '3d4db66e022333ca162b68d8b49023527db4b450520b2fd66a77b056cf6123f1', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (64, 'SHRS-CERT-JSS-2026-000064-F0A24', '719634227201249', 'Allison Ganiyah', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'f0a24a89f3a21966acbf9162fcb50066a0eddc515d60afe8d372135bc3945e90', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (65, 'SHRS-CERT-JSS-2026-000065-F6DBC', '710167004074504', 'Ameerah Abdulhafeez', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'f6dbc48093e514d6e7ca82e8592d8bab421aacf316ed4208b1023dcb476e4ab3', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (66, 'SHRS-CERT-JSS-2026-000066-A58EF', '712878764389035', 'Ameerah Durodola', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'a58efd0b4bdd88dcdd7b1e40da33d95c91ebb263e0cdb51018a98a65b714574c', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (67, 'SHRS-CERT-JSS-2026-000067-2286C', '716123301576828', 'Anisa Opeyemi Jokomba', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '2286cd4b6473c141b85d440192a600d3366de84a90a5829c7867cb86a3d1cd47', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (68, 'SHRS-CERT-JSS-2026-000068-9135F', '710699780947768', 'Baqi Olamiposi Anofi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '9135f3347519a9ec5f7dbee622ca0d742750cc8b91f55ce4a8c294b62fc4db21', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (69, 'SHRS-CERT-JSS-2026-000069-05B08', '713944318135552', 'Faridah Ayomide Aliu', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '05b0827c3f1604bc4910b4a14510b7b6b804a9caaca69babaad5b9a63cdccbd1', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (70, 'SHRS-CERT-JSS-2026-000070-6F953', '719367838764616', 'Fatimah Desire Ibrahim', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '6f95377a5f493460ad4deada457defe04cef3e0896708ff822ecd7151f72055f', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (71, 'SHRS-CERT-JSS-2026-000071-04B3B', '712612375952406', 'Fawaz Owolabi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '04b3b0160a2563da75d04db33d18fac42f2c50c4feb5d4566e721ae0b74a1325', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (72, 'SHRS-CERT-JSS-2026-000072-51814', '714743483445443', 'Hameedah Adebimpe Ojewumi', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '518147fb3836aae264e17d5a94a7b68074a59ebc703b56a04cf9aef99f3bb086', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (73, 'SHRS-CERT-JSS-2026-000073-4A78F', '715856913140191', 'Jubril Lawal', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '4a78f16bb818435a33d82008e16bd3013519793ff57d272bf9254f840d64ef19', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (74, 'SHRS-CERT-JSS-2026-000074-CE1DD', '717455243759974', 'Muhammad Ismail Seriki', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'ce1ddf92510f083f6d615b5a8970080a91496761e0b12485a22ccbf6fa3dbdce', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (75, 'SHRS-CERT-JSS-2026-000075-DD467', '719101450327984', 'Radiah Apatira', 'female', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'dd4674e99a2c29a1f1ddb2fd40e6700d861d6f465cd0537a45421d2f74679cc6', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (76, 'SHRS-CERT-JSS-2026-000076-6D23B', '712345987515770', 'Sa''ad Sanusi', 'male', 'JSS', 'Junior Secondary School · JSS 1 – JSS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '6d23b98d4d91eaa3db1c6bb7ed7f260b60d6585ec9662de674502fc21a330815', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (77, 'SHRS-CERT-SS-2026-000077-BC006', '710433392511139', 'Abdulbasit Amobi Jabarr', 'male', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', 'bc0060183b55ed254da6f0929c03bc17c0a55254394796807163788b7dfc203d', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (78, 'SHRS-CERT-SS-2026-000078-76263', '715590524703564', 'Aisha Shode', 'female', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '762638a6c75b9d4821df49c9ecf6fe7b4436469e3ec12fa5fed964df7a956e8c', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (79, 'SHRS-CERT-SS-2026-000079-3F6AD', '718835061891356', 'Mazeed Hassan-Murtala', 'male', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '3f6ad34678c06c48e2b95dad9e3d3abd8a13d725d0f8bea74fa3ec21c7505a67', 3)
  ON CONFLICT DO NOTHING;
INSERT INTO stage_certificates (id, serial_no, student_identity_no, student_full_name, student_sex, programme_code, programme_label_en, institution_name, academic_year, grade_en, grade_ar, place_en, issued_at, content_hash, hash_key_version) VALUES (80, 'SHRS-CERT-SS-2026-000080-9260B', '717188855323348', 'Thoirah Makinde', 'female', 'SS', 'Senior Secondary School · SS 1 – SS 3', 'Sultan Hanafi Royal Schools — Sultan Hanafi Royal College', '2025/2026', 'Excellent', NULL, 'Ikorodu, Lagos, Nigeria', '2026-08-08', '9260b4bd9395d81800f1d57d24cb06788f91c21bbede43f7d7b6c975cc66014c', 3)
  ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- 3. THE NUMBERING, PROTECTED.
--
--    The engraved number comes from stage_certificate_serial_seq. After this
--    import it must stand at 80, so the next certificate the Registrar
--    issues is 000081 — never a number this batch has already spent, every one of
--    which is the head of its own certificate’s content hash and cannot be
--    re-derived for a different child.
--
--    GREATEST, not a bare setval, for two reasons. It is order-independent,
--    so importing these batches in either order lands in the same place. And
--    it can only move the counter FORWARD: if production has somehow already
--    issued beyond 80, this will not wind it back on top of that work.
--    The value is read from the table, not assumed.
-- ─────────────────────────────────────────────────────────────────────────
SELECT setval('stage_certificate_serial_seq', GREATEST(
  (SELECT COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1]::int), 0) FROM stage_certificates),
  (SELECT last_value FROM stage_certificate_serial_seq)
), true);

--    stage_certificates.id has its own SERIAL sequence, and an INSERT that
--    supplies id explicitly does NOT advance it. Leaving it behind is a
--    silent fault, not a loud one: the next certificate inserts cleanly with
--    id 1, and because the archive reference and the Code 128 payload both
--    derive from cert.id while the engraved number derives from the serial
--    sequence, that certificate would print a barcode naming a different
--    record than its own number.
SELECT setval(pg_get_serial_sequence('stage_certificates', 'id'), GREATEST(
  (SELECT COALESCE(MAX(id), 0) FROM stage_certificates),
  80
), true);

--    The permanent Student ID counter, same discipline. These IDs are for
--    life; re-issuing one to a different child is unrecoverable.
SELECT setval('student_identity_seq', GREATEST(
  (SELECT last_value FROM student_identity_seq), 80
), true);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. THE CHECK THAT MAKES ON CONFLICT DO NOTHING HONEST.
--
--    DO NOTHING is exactly right for re-running an import, and exactly wrong
--    if left unchecked: it will also swallow a genuine collision — a row
--    already occupying one of these ids, or a serial typed in by hand with
--    different content — and report success. So every certificate is read
--    back and compared against what is engraved on the sheet. Serial alone
--    is not enough; the content hash, the printed name and the Student ID
--    are compared too, because a record that merely has the right number
--    while disagreeing about the child is worse than no record.
--
--    Any mismatch raises and the entire transaction rolls back.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  bad text;
  n   int;
BEGIN
  WITH issued(serial_no, content_hash, student_identity_no, student_full_name) AS (VALUES
    ('SHRS-CERT-QUR-2026-000048-64881', '6488133848a46191f61d2043c191a8609eb7b635a1ea9b39899ffcb2e86728b3', '717988020633236', 'Aisha Omoshalewa Anofi'),
    ('SHRS-CERT-QUR-2026-000049-1E924', '1e9243d7cbc60da3bccf82eeef1794999a44cb004afc27e639f05843670553b3', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-QUR-2026-000050-1FBB5', '1fbb5cf55454a4c002ef3b5993bb8067b200393b9b11f8f96789e02f4a5f3796', '716922466886710', 'Zaynab Zakariya Anofi'),
    ('SHRS-CERT-TMH-2026-000051-B6558', 'b65588663012ffb1b5760db18c4e5307a6ea14ebfe708bb70fa2c7b02b3876c2', '711232557821021', 'Abdulbasit Adedokun'),
    ('SHRS-CERT-IBT-2026-000052-21455', '21455e1fdb6c5bc0b49f62663658b5e76d5381813ea06b45a572ae4a842ad8d0', '710167004074504', 'Ameerah Abdulhafeez'),
    ('SHRS-CERT-IBT-2026-000053-DAEF7', 'daef7da163af4312b508bb03d5ae03b49fabc9c289a36a84a44784a3813f8d44', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-IBT-2026-000054-72EF6', '72ef65b35ed95b4182096658a9659e8567fc9147f41ca96a8fdbea3151364269', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-IDD-2026-000055-0CF24', '0cf24ba76de01290f3cf4ff85cf261bfaf04310f662bd1055484450c9e0741e7', '713411541262298', 'Yaseer Balogun'),
    ('SHRS-CERT-PRY-2026-000056-52FC6', '52fc69b02e0bc1d7933fdcd956abde268db88e2b2975354879a72c4944e2a9bd', '716656078450081', 'Aisha Lawal'),
    ('SHRS-CERT-PRY-2026-000057-341A7', '341a7d43a6d7b7bdcabfa7549ebd66a593fccf2b9487ab91a9d1bfc82161c872', '719900615637876', 'Al-ameen Okoh'),
    ('SHRS-CERT-PRY-2026-000058-FE5E3', 'fe5e3baf94e2247798e2cbdd5c8e1290d55a360f38fca50c645c211253b4995e', '717721632196601', 'Ashraf Korede Ojewumi'),
    ('SHRS-CERT-PRY-2026-000059-D277B', 'd277b016be9d57f44431ee73bac897130bb4cbb408d61b602dfd8ca64558bbec', '713145152825668', 'Daud Aliu'),
    ('SHRS-CERT-PRY-2026-000060-B52D7', 'b52d79434105d455b32bcef7a5ac402e8c41b57cd5b0a0868d7c2a69c5cf83ff', '710966169384396', 'Imran Iremide Adegoke'),
    ('SHRS-CERT-PRY-2026-000061-00887', '0088747adb95ce21510243f721dc087eacdc844d1de5ebe7ecca58699a39e8b3', '714477095008816', 'Naheemah Ismail'),
    ('SHRS-CERT-JSS-2026-000062-1EA9D', '1ea9dd059f0a4810a362acf262384cc49219dbc83382f7317f90276643814d84', '716389690013455', 'Abdulrahman Abdullah'),
    ('SHRS-CERT-JSS-2026-000063-3D4DB', '3d4db66e022333ca162b68d8b49023527db4b450520b2fd66a77b056cf6123f1', '717988020633236', 'Aisha Omoshalewa Anofi'),
    ('SHRS-CERT-JSS-2026-000064-F0A24', 'f0a24a89f3a21966acbf9162fcb50066a0eddc515d60afe8d372135bc3945e90', '719634227201249', 'Allison Ganiyah'),
    ('SHRS-CERT-JSS-2026-000065-F6DBC', 'f6dbc48093e514d6e7ca82e8592d8bab421aacf316ed4208b1023dcb476e4ab3', '710167004074504', 'Ameerah Abdulhafeez'),
    ('SHRS-CERT-JSS-2026-000066-A58EF', 'a58efd0b4bdd88dcdd7b1e40da33d95c91ebb263e0cdb51018a98a65b714574c', '712878764389035', 'Ameerah Durodola'),
    ('SHRS-CERT-JSS-2026-000067-2286C', '2286cd4b6473c141b85d440192a600d3366de84a90a5829c7867cb86a3d1cd47', '716123301576828', 'Anisa Opeyemi Jokomba'),
    ('SHRS-CERT-JSS-2026-000068-9135F', '9135f3347519a9ec5f7dbee622ca0d742750cc8b91f55ce4a8c294b62fc4db21', '710699780947768', 'Baqi Olamiposi Anofi'),
    ('SHRS-CERT-JSS-2026-000069-05B08', '05b0827c3f1604bc4910b4a14510b7b6b804a9caaca69babaad5b9a63cdccbd1', '713944318135552', 'Faridah Ayomide Aliu'),
    ('SHRS-CERT-JSS-2026-000070-6F953', '6f95377a5f493460ad4deada457defe04cef3e0896708ff822ecd7151f72055f', '719367838764616', 'Fatimah Desire Ibrahim'),
    ('SHRS-CERT-JSS-2026-000071-04B3B', '04b3b0160a2563da75d04db33d18fac42f2c50c4feb5d4566e721ae0b74a1325', '712612375952406', 'Fawaz Owolabi'),
    ('SHRS-CERT-JSS-2026-000072-51814', '518147fb3836aae264e17d5a94a7b68074a59ebc703b56a04cf9aef99f3bb086', '714743483445443', 'Hameedah Adebimpe Ojewumi'),
    ('SHRS-CERT-JSS-2026-000073-4A78F', '4a78f16bb818435a33d82008e16bd3013519793ff57d272bf9254f840d64ef19', '715856913140191', 'Jubril Lawal'),
    ('SHRS-CERT-JSS-2026-000074-CE1DD', 'ce1ddf92510f083f6d615b5a8970080a91496761e0b12485a22ccbf6fa3dbdce', '717455243759974', 'Muhammad Ismail Seriki'),
    ('SHRS-CERT-JSS-2026-000075-DD467', 'dd4674e99a2c29a1f1ddb2fd40e6700d861d6f465cd0537a45421d2f74679cc6', '719101450327984', 'Radiah Apatira'),
    ('SHRS-CERT-JSS-2026-000076-6D23B', '6d23b98d4d91eaa3db1c6bb7ed7f260b60d6585ec9662de674502fc21a330815', '712345987515770', 'Sa''''ad Sanusi'),
    ('SHRS-CERT-SS-2026-000077-BC006', 'bc0060183b55ed254da6f0929c03bc17c0a55254394796807163788b7dfc203d', '710433392511139', 'Abdulbasit Amobi Jabarr'),
    ('SHRS-CERT-SS-2026-000078-76263', '762638a6c75b9d4821df49c9ecf6fe7b4436469e3ec12fa5fed964df7a956e8c', '715590524703564', 'Aisha Shode'),
    ('SHRS-CERT-SS-2026-000079-3F6AD', '3f6ad34678c06c48e2b95dad9e3d3abd8a13d725d0f8bea74fa3ec21c7505a67', '718835061891356', 'Mazeed Hassan-Murtala'),
    ('SHRS-CERT-SS-2026-000080-9260B', '9260b4bd9395d81800f1d57d24cb06788f91c21bbede43f7d7b6c975cc66014c', '717188855323348', 'Thoirah Makinde')
  )
  SELECT string_agg(issued.serial_no || ' — ' || reason, E'\n    '), count(*)
    INTO bad, n
  FROM issued
  CROSS JOIN LATERAL (
    SELECT CASE
      WHEN c.id IS NULL THEN 'no record on file after import'
      WHEN lower(c.content_hash) IS DISTINCT FROM lower(issued.content_hash)
        THEN 'record content hash disagrees with the certificate'
      WHEN c.student_full_name IS DISTINCT FROM issued.student_full_name
        THEN 'record names ' || COALESCE(c.student_full_name, '(null)')
             || ', certificate names ' || issued.student_full_name
      WHEN c.student_identity_no IS DISTINCT FROM issued.student_identity_no
        THEN 'record Student ID disagrees with the certificate'
    END AS reason
    FROM (SELECT 1) _
    LEFT JOIN stage_certificates c ON c.serial_no = issued.serial_no
  ) chk
  WHERE chk.reason IS NOT NULL;

  IF n > 0 THEN
    RAISE EXCEPTION E'IMPORT ABORTED — % certificate(s) do not agree with the issued documents:\n    %', n, bad;
  END IF;

  IF (SELECT last_value FROM stage_certificate_serial_seq) < 80 THEN
    RAISE EXCEPTION 'IMPORT ABORTED — serial sequence stands at %, below the highest issued number 80. The next certificate would re-use a printed number.',
      (SELECT last_value FROM stage_certificate_serial_seq);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- 5. AFTER-STATE, and the one thing that legitimately needs a human.
--    Any child listed under "student record not linked" holds a valid
--    certificate that verifies correctly; their row in students is simply
--    missing or filed under a different spelling. Give the list to the
--    Registrar's Office. Do not edit this file to force a match.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 'AFTER   certificates on file' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'AFTER   highest engraved number',
  COALESCE(MAX((regexp_match(serial_no, '-(\d{6})-'))[1])::text, '(none)') FROM stage_certificates
UNION ALL SELECT 'AFTER   serial sequence stands at', last_value::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   next certificate will be', (last_value + 1)::text FROM stage_certificate_serial_seq
UNION ALL SELECT 'AFTER   student id sequence stands at', last_value::text FROM student_identity_seq;

SELECT 'student record not linked' AS check, c.student_full_name AS value
FROM stage_certificates c
WHERE c.serial_no IN ('SHRS-CERT-QUR-2026-000048-64881', 'SHRS-CERT-QUR-2026-000049-1E924', 'SHRS-CERT-QUR-2026-000050-1FBB5', 'SHRS-CERT-TMH-2026-000051-B6558', 'SHRS-CERT-IBT-2026-000052-21455', 'SHRS-CERT-IBT-2026-000053-DAEF7', 'SHRS-CERT-IBT-2026-000054-72EF6', 'SHRS-CERT-IDD-2026-000055-0CF24', 'SHRS-CERT-PRY-2026-000056-52FC6', 'SHRS-CERT-PRY-2026-000057-341A7', 'SHRS-CERT-PRY-2026-000058-FE5E3', 'SHRS-CERT-PRY-2026-000059-D277B', 'SHRS-CERT-PRY-2026-000060-B52D7', 'SHRS-CERT-PRY-2026-000061-00887', 'SHRS-CERT-JSS-2026-000062-1EA9D', 'SHRS-CERT-JSS-2026-000063-3D4DB', 'SHRS-CERT-JSS-2026-000064-F0A24', 'SHRS-CERT-JSS-2026-000065-F6DBC', 'SHRS-CERT-JSS-2026-000066-A58EF', 'SHRS-CERT-JSS-2026-000067-2286C', 'SHRS-CERT-JSS-2026-000068-9135F', 'SHRS-CERT-JSS-2026-000069-05B08', 'SHRS-CERT-JSS-2026-000070-6F953', 'SHRS-CERT-JSS-2026-000071-04B3B', 'SHRS-CERT-JSS-2026-000072-51814', 'SHRS-CERT-JSS-2026-000073-4A78F', 'SHRS-CERT-JSS-2026-000074-CE1DD', 'SHRS-CERT-JSS-2026-000075-DD467', 'SHRS-CERT-JSS-2026-000076-6D23B', 'SHRS-CERT-SS-2026-000077-BC006', 'SHRS-CERT-SS-2026-000078-76263', 'SHRS-CERT-SS-2026-000079-3F6AD', 'SHRS-CERT-SS-2026-000080-9260B')
  AND NOT EXISTS (
    SELECT 1 FROM students s WHERE s.identity_no = c.student_identity_no
  )
ORDER BY 2;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- NOT FINISHED HERE. A successful import is not a working verification page.
-- Prove it against the real public endpoint before telling anyone it is
-- fixed, and before any further sheet is released:
--
--     node scripts/verify-issued-certificates-live.mjs --full
-- ─────────────────────────────────────────────────────────────────────────
