-- SHRS — INSTITUTION CREDENTIAL ID ASSIGNMENT
-- Generated by scripts/build-credential-ids.mjs from the published registers.
--
-- 49 certificates. 33 carry this value in their own sealed register
-- already (minted 15 Aug 2026, ICID written at issuance); for those the UPDATE
-- below changes nothing and exists to PROVE the issuance path and the
-- derivation agree. The remaining 16 predate the column and are pinned here.
--
-- The ICID is UUIDv5(stored serial, SHRS namespace) — see
-- functions/_lib/credential-id.js for why it is derived rather than random.
-- It is never printed on a certificate and never returned to the public.
--
-- SAFE TO RUN REPEATEDLY. Every value is a pure function of a serial that is
-- engraved on paper and cannot change, so a second run writes the same values.
--
-- ONE TRANSACTION, with an assertion at the end.

BEGIN;

UPDATE stage_certificates SET credential_id = 'b77b1a02-797d-552b-b5b9-f4b4aae5a25c'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000035-368DC';  -- Hameedah Adebimpe Ojewumi
UPDATE stage_certificates SET credential_id = '10bf0031-bc1b-580f-accb-ee6c69704c8c'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000036-B9E10';  -- Aisha Anofi
UPDATE stage_certificates SET credential_id = '89328af3-b756-5596-b904-75ec016a1277'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000037-22C49';  -- Abdulbasit Adedokun
UPDATE stage_certificates SET credential_id = '061b7f7d-f0ec-51cd-8ee1-afc2cef4c168'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000038-2944F';  -- Naheemah Ismail
UPDATE stage_certificates SET credential_id = '83a7321f-47ba-5abb-a22f-36afaeae1305'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000039-518A8';  -- Ashrof Akorede
UPDATE stage_certificates SET credential_id = '9d1e403d-cdc0-50aa-ac5b-a4c8c707e316'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000040-60DAF';  -- Imran Adegoke
UPDATE stage_certificates SET credential_id = '835e27e5-c7a8-5781-880f-edae9fe76201'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000041-6F66F';  -- Abdulateef Adedokun
UPDATE stage_certificates SET credential_id = 'ac106a8e-010d-5c22-b92c-867a8a99cbd2'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000048-0B67B';  -- issued live 2026-08-16 (IBT)
UPDATE stage_certificates SET credential_id = '40e6c648-7b63-5c43-8b61-2bb91083c01e'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000055-1F758';  -- Ameerah Abdulhafeez
UPDATE stage_certificates SET credential_id = '559ab3d1-21ab-5695-b02f-b89242f874c3'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000056-C1244';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = '37a0d8a5-cff6-55e0-a324-f526f169affb'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000057-91D78';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '4faf90d7-6a22-5f00-8b04-63db084d9845'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000042-56798';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '0fb29e10-ecf4-5b26-b18d-ba857ccde322'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000043-6EEAF';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = 'a74ad80e-7fe9-5d15-a31a-cdb388e8b9cb'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000044-8B125';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = 'bcd05722-edb0-5aba-987f-520f3c528e17'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000045-F546F';  -- Thoirah Makinde
UPDATE stage_certificates SET credential_id = '715854e9-9744-5d26-b843-5c797d99fec0'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000046-7E37A';  -- Abdulbasit Amobi Jabarr
UPDATE stage_certificates SET credential_id = 'afa918e7-4300-586f-b52e-53525f32b08d'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000047-CB9F5';  -- Abdullah Oladimeji Anofi
UPDATE stage_certificates SET credential_id = '4d9a79fa-656b-547d-80cb-4beccb4bfd1b'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000049-0BEE7';  -- issued live 2026-08-21 (IDD)
UPDATE stage_certificates SET credential_id = 'f9241001-f497-53c9-9281-3c780ef2e5ae'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000058-C6381';  -- Yaseer Balogun
UPDATE stage_certificates SET credential_id = '95986098-483f-50a2-aee1-63129a88e93c'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000065-48606';  -- Abdulrahman Abdullah
UPDATE stage_certificates SET credential_id = '32cfea0b-5837-50bc-8de0-cbb6ff20db43'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000066-C52E5';  -- Aisha Omoshalewa Anofi
UPDATE stage_certificates SET credential_id = '60a0bf86-df08-58e1-832a-422a8be3f229'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000067-9C9B2';  -- Allison Ganiyah
UPDATE stage_certificates SET credential_id = '29c5cd9e-6b1d-52a2-bf4c-2d4e5b22af69'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000068-65F5F';  -- Ameerah Abdulhafeez
UPDATE stage_certificates SET credential_id = '1a2496f6-e8ef-5b15-8380-b617f3845fd9'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000069-77D29';  -- Ameerah Durodola
UPDATE stage_certificates SET credential_id = '6ec1c72c-7c2a-569e-a69b-f0de4dd7339d'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000070-2D5A6';  -- Anisa Opeyemi Jokomba
UPDATE stage_certificates SET credential_id = '0f74cf88-15fe-51c1-aa69-ccd097fd55d2'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000071-14CDF';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = '2b2a298a-6239-5ecf-9ee0-375abc74760a'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000072-8EF9D';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = '9f744b41-ce25-5a46-873c-8421b7a44a99'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000073-2C155';  -- Fatimah Desire Ibrahim
UPDATE stage_certificates SET credential_id = '084be30f-45e6-5eb5-a31f-496d353c650b'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000074-23BC0';  -- Fawaz Owolabi
UPDATE stage_certificates SET credential_id = '69470a21-05d9-59a0-b2d0-cd018e593d47'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000075-0F568';  -- Hameedah Adebimpe Ojewumi
UPDATE stage_certificates SET credential_id = 'c2d5a744-da8a-576b-a06e-16d88282fd0d'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000076-B151F';  -- Jubril Lawal
UPDATE stage_certificates SET credential_id = '02c15237-9429-580c-9e9c-6cd78187be4c'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000077-FBCD3';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '589ad2a1-deb4-5a4f-a82f-06fbc4949b55'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000078-2EE5D';  -- Radiah Apatira
UPDATE stage_certificates SET credential_id = '5a710d09-56f1-52fb-8f8f-ea877aa7fc37'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000079-163F2';  -- Sa'ad Sanusi
UPDATE stage_certificates SET credential_id = '9445d630-6454-58dc-a71a-60b8a8701dd3'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000059-C7997';  -- Aisha Lawal
UPDATE stage_certificates SET credential_id = '99c1c327-8452-596b-88d2-15e806727c82'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000060-F3021';  -- Al-ameen Okoh
UPDATE stage_certificates SET credential_id = 'f252e986-0b78-5d14-9f0d-2a15893a49a2'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000061-33E36';  -- Ashraf Korede Ojewumi
UPDATE stage_certificates SET credential_id = '79c7eda4-467c-5875-9870-166388875e5a'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000062-91BD3';  -- Daud Aliu
UPDATE stage_certificates SET credential_id = '0bd1e0b8-f9c1-552c-ad54-d0aaf28d226f'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000063-E9A53';  -- Imran Iremide Adegoke
UPDATE stage_certificates SET credential_id = '57dad779-855d-5a47-9b28-f72c0047b74d'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000064-B2C46';  -- Naheemah Ismail
UPDATE stage_certificates SET credential_id = '813e02e7-d90b-5bcc-bf81-642e71088309'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000051-890BF';  -- Aisha Omoshalewa Anofi
UPDATE stage_certificates SET credential_id = '4d3a35db-442d-5d42-bb10-cd77b23429ab'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000052-0BFD3';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = 'c86a85f8-2723-5ff5-aae5-fbe141653b38'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000053-7556C';  -- Zaynab Zakariya Anofi
UPDATE stage_certificates SET credential_id = '3b1184c1-36b7-57e7-b0f7-c88f55077d76'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000080-29DD5';  -- Abdulbasit Amobi Jabarr
UPDATE stage_certificates SET credential_id = '6bc8e0aa-ddf6-5f66-91c4-410537c85867'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000081-A3178';  -- Aisha Shode
UPDATE stage_certificates SET credential_id = '3e3610a8-bb73-5904-87e6-a613cd919b41'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000082-5CC78';  -- Mazeed Hassan-Murtala
UPDATE stage_certificates SET credential_id = '2343c9f0-744d-5c0d-ac58-c6e1d0a6cebf'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000083-AA6F4';  -- Thoirah Makinde
UPDATE stage_certificates SET credential_id = 'bc413496-9c7c-5bc2-8bab-3a61b5477fe5'::uuid
  WHERE serial_no = 'SHRS-CERT-THN-2026-000050-62EEC';  -- issued live 2026-08-21 (THN)
UPDATE stage_certificates SET credential_id = '795124d7-7eb2-5745-8776-053fd4b23008'::uuid
  WHERE serial_no = 'SHRS-CERT-TMH-2026-000054-7CC6F';  -- Abdulbasit Adedokun

-- ─────────────────────────────────────────────────────────────────────────
-- THE ASSERTION. Two ways this could go wrong quietly, both checked:
--
--   1. A certificate on file carries an ICID that is NOT in the list above —
--      meaning it is still holding the database-generated default, and the
--      permanent identifier is an accident of which environment inserted it.
--   2. Two certificates share one. UNIQUE would already have refused the
--      write, but reporting it here names the pair instead of raising 23505.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  stray text;
  n    int;
BEGIN
  SELECT string_agg(serial_no, E'\n    '), count(*) INTO stray, n
  FROM stage_certificates
  WHERE credential_id NOT IN (
    'b77b1a02-797d-552b-b5b9-f4b4aae5a25c'::uuid,
    '10bf0031-bc1b-580f-accb-ee6c69704c8c'::uuid,
    '89328af3-b756-5596-b904-75ec016a1277'::uuid,
    '061b7f7d-f0ec-51cd-8ee1-afc2cef4c168'::uuid,
    '83a7321f-47ba-5abb-a22f-36afaeae1305'::uuid,
    '9d1e403d-cdc0-50aa-ac5b-a4c8c707e316'::uuid,
    '835e27e5-c7a8-5781-880f-edae9fe76201'::uuid,
    'ac106a8e-010d-5c22-b92c-867a8a99cbd2'::uuid,
    '40e6c648-7b63-5c43-8b61-2bb91083c01e'::uuid,
    '559ab3d1-21ab-5695-b02f-b89242f874c3'::uuid,
    '37a0d8a5-cff6-55e0-a324-f526f169affb'::uuid,
    '4faf90d7-6a22-5f00-8b04-63db084d9845'::uuid,
    '0fb29e10-ecf4-5b26-b18d-ba857ccde322'::uuid,
    'a74ad80e-7fe9-5d15-a31a-cdb388e8b9cb'::uuid,
    'bcd05722-edb0-5aba-987f-520f3c528e17'::uuid,
    '715854e9-9744-5d26-b843-5c797d99fec0'::uuid,
    'afa918e7-4300-586f-b52e-53525f32b08d'::uuid,
    '4d9a79fa-656b-547d-80cb-4beccb4bfd1b'::uuid,
    'f9241001-f497-53c9-9281-3c780ef2e5ae'::uuid,
    '95986098-483f-50a2-aee1-63129a88e93c'::uuid,
    '32cfea0b-5837-50bc-8de0-cbb6ff20db43'::uuid,
    '60a0bf86-df08-58e1-832a-422a8be3f229'::uuid,
    '29c5cd9e-6b1d-52a2-bf4c-2d4e5b22af69'::uuid,
    '1a2496f6-e8ef-5b15-8380-b617f3845fd9'::uuid,
    '6ec1c72c-7c2a-569e-a69b-f0de4dd7339d'::uuid,
    '0f74cf88-15fe-51c1-aa69-ccd097fd55d2'::uuid,
    '2b2a298a-6239-5ecf-9ee0-375abc74760a'::uuid,
    '9f744b41-ce25-5a46-873c-8421b7a44a99'::uuid,
    '084be30f-45e6-5eb5-a31f-496d353c650b'::uuid,
    '69470a21-05d9-59a0-b2d0-cd018e593d47'::uuid,
    'c2d5a744-da8a-576b-a06e-16d88282fd0d'::uuid,
    '02c15237-9429-580c-9e9c-6cd78187be4c'::uuid,
    '589ad2a1-deb4-5a4f-a82f-06fbc4949b55'::uuid,
    '5a710d09-56f1-52fb-8f8f-ea877aa7fc37'::uuid,
    '9445d630-6454-58dc-a71a-60b8a8701dd3'::uuid,
    '99c1c327-8452-596b-88d2-15e806727c82'::uuid,
    'f252e986-0b78-5d14-9f0d-2a15893a49a2'::uuid,
    '79c7eda4-467c-5875-9870-166388875e5a'::uuid,
    '0bd1e0b8-f9c1-552c-ad54-d0aaf28d226f'::uuid,
    '57dad779-855d-5a47-9b28-f72c0047b74d'::uuid,
    '813e02e7-d90b-5bcc-bf81-642e71088309'::uuid,
    '4d3a35db-442d-5d42-bb10-cd77b23429ab'::uuid,
    'c86a85f8-2723-5ff5-aae5-fbe141653b38'::uuid,
    '3b1184c1-36b7-57e7-b0f7-c88f55077d76'::uuid,
    '6bc8e0aa-ddf6-5f66-91c4-410537c85867'::uuid,
    '3e3610a8-bb73-5904-87e6-a613cd919b41'::uuid,
    '2343c9f0-744d-5c0d-ac58-c6e1d0a6cebf'::uuid,
    'bc413496-9c7c-5bc2-8bab-3a61b5477fe5'::uuid,
    '795124d7-7eb2-5745-8776-053fd4b23008'::uuid
  );
  IF n > 0 THEN
    RAISE EXCEPTION E'ABORTED — % certificate(s) still carry a database-generated ICID rather than their derived one:\n    %', n, stray;
  END IF;
END $$;

SELECT 'credential ids assigned' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'distinct credential ids', count(DISTINCT credential_id)::text FROM stage_certificates;

COMMIT;
