-- SHRS — INSTITUTION CREDENTIAL ID ASSIGNMENT
-- Generated by scripts/build-credential-ids.mjs from the published registers.
--
-- 46 certificates. 33 carry this value in their own sealed register
-- already (minted 15 Aug 2026, ICID written at issuance); for those the UPDATE
-- below changes nothing and exists to PROVE the issuance path and the
-- derivation agree. The remaining 13 predate the column and are pinned here.
--
-- The ICID is UUIDv5(stored serial, SHRS namespace) — see
-- functions/_lib/credential-id.js for why it is derived rather than random.
-- It is never printed on a certificate and never returned to the public.
--
-- SAFE TO RUN REPEATEDLY. Every value is a pure function of a serial that is
-- engraved on paper and cannot change, so a second run writes the same values.
--
-- ONE TRANSACTION, with an assertion at the end.

BEGIN;

UPDATE stage_certificates SET credential_id = 'b77b1a02-797d-552b-b5b9-f4b4aae5a25c'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000035-368DC';  -- Hameedah Adebimpe Ojewumi
UPDATE stage_certificates SET credential_id = '10bf0031-bc1b-580f-accb-ee6c69704c8c'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000036-B9E10';  -- Aisha Anofi
UPDATE stage_certificates SET credential_id = '89328af3-b756-5596-b904-75ec016a1277'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000037-22C49';  -- Abdulbasit Adedokun
UPDATE stage_certificates SET credential_id = '061b7f7d-f0ec-51cd-8ee1-afc2cef4c168'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000038-2944F';  -- Naheemah Ismail
UPDATE stage_certificates SET credential_id = '83a7321f-47ba-5abb-a22f-36afaeae1305'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000039-518A8';  -- Ashrof Akorede
UPDATE stage_certificates SET credential_id = '9d1e403d-cdc0-50aa-ac5b-a4c8c707e316'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000040-60DAF';  -- Imran Adegoke
UPDATE stage_certificates SET credential_id = '835e27e5-c7a8-5781-880f-edae9fe76201'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000041-6F66F';  -- Abdulateef Adedokun
UPDATE stage_certificates SET credential_id = '0f51015e-cdea-5beb-8ed4-577f80cac38d'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000052-21455';  -- Ameerah Abdulhafeez
UPDATE stage_certificates SET credential_id = 'b107d3f6-7a90-5226-b8f7-1864fe14095b'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000053-DAEF7';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = '73a1df58-f84d-56c4-960b-b1305f23625f'::uuid
  WHERE serial_no = 'SHRS-CERT-IBT-2026-000054-72EF6';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '4faf90d7-6a22-5f00-8b04-63db084d9845'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000042-56798';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '0fb29e10-ecf4-5b26-b18d-ba857ccde322'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000043-6EEAF';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = 'a74ad80e-7fe9-5d15-a31a-cdb388e8b9cb'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000044-8B125';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = 'bcd05722-edb0-5aba-987f-520f3c528e17'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000045-F546F';  -- Thoirah Makinde
UPDATE stage_certificates SET credential_id = '715854e9-9744-5d26-b843-5c797d99fec0'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000046-7E37A';  -- Abdulbasit Amobi Jabarr
UPDATE stage_certificates SET credential_id = 'afa918e7-4300-586f-b52e-53525f32b08d'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000047-CB9F5';  -- Abdullah Oladimeji Anofi
UPDATE stage_certificates SET credential_id = '148d6a3f-cff4-5870-a6e9-39b5e6a68bd4'::uuid
  WHERE serial_no = 'SHRS-CERT-IDD-2026-000055-0CF24';  -- Yaseer Balogun
UPDATE stage_certificates SET credential_id = '5fbecf7f-3485-59ec-8a1b-b2fcaaa6b125'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000062-1EA9D';  -- Abdulrahman Abdullah
UPDATE stage_certificates SET credential_id = '7d9ef26b-e0b1-5b04-a30f-28989894f4b4'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000063-3D4DB';  -- Aisha Omoshalewa Anofi
UPDATE stage_certificates SET credential_id = '69467331-9144-56ab-a280-56cb6d4597c2'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000064-F0A24';  -- Allison Ganiyah
UPDATE stage_certificates SET credential_id = '9655a84f-a296-5fea-93b8-fe19dc2346d5'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000065-F6DBC';  -- Ameerah Abdulhafeez
UPDATE stage_certificates SET credential_id = 'aca9596e-c24d-53f8-ba0c-9abe22f580cd'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000066-A58EF';  -- Ameerah Durodola
UPDATE stage_certificates SET credential_id = '03863597-85d1-5455-b40a-de6849dbdb11'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000067-2286C';  -- Anisa Opeyemi Jokomba
UPDATE stage_certificates SET credential_id = '88a3b9aa-bf56-51c2-8a16-c9a18a060cd5'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000068-9135F';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = '45bfd040-9990-5242-b1a0-5a3a2842c07b'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000069-05B08';  -- Faridah Ayomide Aliu
UPDATE stage_certificates SET credential_id = 'fc7e0273-4c9e-5bd8-964d-082d24cfbb02'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000070-6F953';  -- Fatimah Desire Ibrahim
UPDATE stage_certificates SET credential_id = '7b052883-38d0-580e-a7bd-4ff7b174cc0d'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000071-04B3B';  -- Fawaz Owolabi
UPDATE stage_certificates SET credential_id = 'cebf43bd-2b8c-5551-be6f-d903d6e6a3fe'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000072-51814';  -- Hameedah Adebimpe Ojewumi
UPDATE stage_certificates SET credential_id = '3d4d24ce-15fe-57b0-b66e-5c91b1707aae'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000073-4A78F';  -- Jubril Lawal
UPDATE stage_certificates SET credential_id = '3065b33a-203a-51f3-bc83-9312936facbc'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000074-CE1DD';  -- Muhammad Ismail Seriki
UPDATE stage_certificates SET credential_id = '0908840f-9781-5df6-ba64-b13b2f7860c0'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000075-DD467';  -- Radiah Apatira
UPDATE stage_certificates SET credential_id = '2c18330d-3ee4-5b8d-8246-94947005848d'::uuid
  WHERE serial_no = 'SHRS-CERT-JSS-2026-000076-6D23B';  -- Sa'ad Sanusi
UPDATE stage_certificates SET credential_id = 'cc453f5d-9b76-5a80-9679-5e6398f9d589'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000056-52FC6';  -- Aisha Lawal
UPDATE stage_certificates SET credential_id = '1a8b1eac-65ec-5d35-9f7e-d9689ad9a9eb'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000057-341A7';  -- Al-ameen Okoh
UPDATE stage_certificates SET credential_id = 'e9731034-d6d5-5740-afe6-69701b21cb10'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000058-FE5E3';  -- Ashraf Korede Ojewumi
UPDATE stage_certificates SET credential_id = '8a59683c-36dd-580f-9967-dea018676319'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000059-D277B';  -- Daud Aliu
UPDATE stage_certificates SET credential_id = '4c1c6c18-79f9-5f0f-9b6a-d454d83e7469'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000060-B52D7';  -- Imran Iremide Adegoke
UPDATE stage_certificates SET credential_id = '0c8f4bb9-7ec9-5abe-9f98-bff60159b9f6'::uuid
  WHERE serial_no = 'SHRS-CERT-PRY-2026-000061-00887';  -- Naheemah Ismail
UPDATE stage_certificates SET credential_id = 'f87e5a9a-8d5a-5ed2-8db4-f1d870022aa0'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000048-64881';  -- Aisha Omoshalewa Anofi
UPDATE stage_certificates SET credential_id = '01c27ca7-532d-510d-9599-b3eed949ca9f'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000049-1E924';  -- Baqi Olamiposi Anofi
UPDATE stage_certificates SET credential_id = '64047284-0043-5313-9eea-c952f9bd06dd'::uuid
  WHERE serial_no = 'SHRS-CERT-QUR-2026-000050-1FBB5';  -- Zaynab Zakariya Anofi
UPDATE stage_certificates SET credential_id = '6dff2c42-b05a-5acc-b638-4725235d551b'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000077-BC006';  -- Abdulbasit Amobi Jabarr
UPDATE stage_certificates SET credential_id = '4463c322-cde8-548c-a7b5-24427deb9840'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000078-76263';  -- Aisha Shode
UPDATE stage_certificates SET credential_id = '3433a325-3dc3-557e-8f62-1d7a87dd8b4c'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000079-3F6AD';  -- Mazeed Hassan-Murtala
UPDATE stage_certificates SET credential_id = '0efda1a2-4b7b-589d-8b4d-50f0fe96d543'::uuid
  WHERE serial_no = 'SHRS-CERT-SS-2026-000080-9260B';  -- Thoirah Makinde
UPDATE stage_certificates SET credential_id = '171671e3-56dc-5d93-9b27-afda0a903f00'::uuid
  WHERE serial_no = 'SHRS-CERT-TMH-2026-000051-B6558';  -- Abdulbasit Adedokun

-- ─────────────────────────────────────────────────────────────────────────
-- THE ASSERTION. Two ways this could go wrong quietly, both checked:
--
--   1. A certificate on file carries an ICID that is NOT in the list above —
--      meaning it is still holding the database-generated default, and the
--      permanent identifier is an accident of which environment inserted it.
--   2. Two certificates share one. UNIQUE would already have refused the
--      write, but reporting it here names the pair instead of raising 23505.
-- ─────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  stray text;
  n    int;
BEGIN
  SELECT string_agg(serial_no, E'\n    '), count(*) INTO stray, n
  FROM stage_certificates
  WHERE credential_id NOT IN (
    'b77b1a02-797d-552b-b5b9-f4b4aae5a25c'::uuid,
    '10bf0031-bc1b-580f-accb-ee6c69704c8c'::uuid,
    '89328af3-b756-5596-b904-75ec016a1277'::uuid,
    '061b7f7d-f0ec-51cd-8ee1-afc2cef4c168'::uuid,
    '83a7321f-47ba-5abb-a22f-36afaeae1305'::uuid,
    '9d1e403d-cdc0-50aa-ac5b-a4c8c707e316'::uuid,
    '835e27e5-c7a8-5781-880f-edae9fe76201'::uuid,
    '0f51015e-cdea-5beb-8ed4-577f80cac38d'::uuid,
    'b107d3f6-7a90-5226-b8f7-1864fe14095b'::uuid,
    '73a1df58-f84d-56c4-960b-b1305f23625f'::uuid,
    '4faf90d7-6a22-5f00-8b04-63db084d9845'::uuid,
    '0fb29e10-ecf4-5b26-b18d-ba857ccde322'::uuid,
    'a74ad80e-7fe9-5d15-a31a-cdb388e8b9cb'::uuid,
    'bcd05722-edb0-5aba-987f-520f3c528e17'::uuid,
    '715854e9-9744-5d26-b843-5c797d99fec0'::uuid,
    'afa918e7-4300-586f-b52e-53525f32b08d'::uuid,
    '148d6a3f-cff4-5870-a6e9-39b5e6a68bd4'::uuid,
    '5fbecf7f-3485-59ec-8a1b-b2fcaaa6b125'::uuid,
    '7d9ef26b-e0b1-5b04-a30f-28989894f4b4'::uuid,
    '69467331-9144-56ab-a280-56cb6d4597c2'::uuid,
    '9655a84f-a296-5fea-93b8-fe19dc2346d5'::uuid,
    'aca9596e-c24d-53f8-ba0c-9abe22f580cd'::uuid,
    '03863597-85d1-5455-b40a-de6849dbdb11'::uuid,
    '88a3b9aa-bf56-51c2-8a16-c9a18a060cd5'::uuid,
    '45bfd040-9990-5242-b1a0-5a3a2842c07b'::uuid,
    'fc7e0273-4c9e-5bd8-964d-082d24cfbb02'::uuid,
    '7b052883-38d0-580e-a7bd-4ff7b174cc0d'::uuid,
    'cebf43bd-2b8c-5551-be6f-d903d6e6a3fe'::uuid,
    '3d4d24ce-15fe-57b0-b66e-5c91b1707aae'::uuid,
    '3065b33a-203a-51f3-bc83-9312936facbc'::uuid,
    '0908840f-9781-5df6-ba64-b13b2f7860c0'::uuid,
    '2c18330d-3ee4-5b8d-8246-94947005848d'::uuid,
    'cc453f5d-9b76-5a80-9679-5e6398f9d589'::uuid,
    '1a8b1eac-65ec-5d35-9f7e-d9689ad9a9eb'::uuid,
    'e9731034-d6d5-5740-afe6-69701b21cb10'::uuid,
    '8a59683c-36dd-580f-9967-dea018676319'::uuid,
    '4c1c6c18-79f9-5f0f-9b6a-d454d83e7469'::uuid,
    '0c8f4bb9-7ec9-5abe-9f98-bff60159b9f6'::uuid,
    'f87e5a9a-8d5a-5ed2-8db4-f1d870022aa0'::uuid,
    '01c27ca7-532d-510d-9599-b3eed949ca9f'::uuid,
    '64047284-0043-5313-9eea-c952f9bd06dd'::uuid,
    '6dff2c42-b05a-5acc-b638-4725235d551b'::uuid,
    '4463c322-cde8-548c-a7b5-24427deb9840'::uuid,
    '3433a325-3dc3-557e-8f62-1d7a87dd8b4c'::uuid,
    '0efda1a2-4b7b-589d-8b4d-50f0fe96d543'::uuid,
    '171671e3-56dc-5d93-9b27-afda0a903f00'::uuid
  );
  IF n > 0 THEN
    RAISE EXCEPTION E'ABORTED — % certificate(s) still carry a database-generated ICID rather than their derived one:\n    %', n, stray;
  END IF;
END $$;

SELECT 'credential ids assigned' AS check, count(*)::text AS value FROM stage_certificates
UNION ALL SELECT 'distinct credential ids', count(DISTINCT credential_id)::text FROM stage_certificates;

COMMIT;
